# Generated by Django 5.2.12 on 2026-07-16 11:26

import apps.orientation_feedback.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0010_facultyassignmentreplacementlog'),
        ('rbac', '0029_seed_orientation_feedback_permissions'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('section_code', models.CharField(max_length=16)),
                ('section_title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('SCALE', 'Five-point scale'), ('MULTI_SELECT', 'Multiple selection'), ('TEXT', 'Open feedback')], max_length=16)),
                ('scale_kind', models.CharField(blank=True, choices=[('QUALITY', 'Quality'), ('EASE', 'Ease'), ('CLARITY', 'Clarity'), ('PACE', 'Pace'), ('CONFIDENCE', 'Confidence'), ('READINESS', 'Readiness'), ('AGREEMENT', 'Agreement')], max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('reverse_scored', models.BooleanField(default=False)),
                ('composite_index_code', models.CharField(blank=True, max_length=64)),
                ('display_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'orientation_feedback_questions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrientationSurveyEligibleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientation_feedback_eligibility_links', to='rbac.role')),
            ],
            options={
                'db_table': 'orientation_feedback_eligible_roles',
            },
        ),
        migrations.CreateModel(
            name='OrientationSurveyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_role_codes_snapshot', models.JSONField(blank=True, default=list)),
                ('validation_method', models.CharField(choices=[('EMAIL', 'Registered email')], default='EMAIL', max_length=16)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientation_feedback_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orientation_feedback_participations',
            },
        ),
        migrations.CreateModel(
            name='OrientationSurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, max_length=16)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField()),
                ('allows_other_text', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orientation_feedback.orientationsurveyquestion')),
            ],
            options={
                'db_table': 'orientation_feedback_choices',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrientationSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='orientation_feedback.orientationsurveyparticipation')),
            ],
            options={
                'db_table': 'orientation_feedback_responses',
                'ordering': ['submitted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrientationSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='orientation_feedback.orientationsurveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='orientation_feedback.orientationsurveyresponse')),
            ],
            options={
                'db_table': 'orientation_feedback_answers',
            },
        ),
        migrations.CreateModel(
            name='OrientationSurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('survey_type', models.CharField(choices=[('FACULTY', 'Faculty Orientation Feedback'), ('ACADEMIC_HEADS', 'Academic Heads Orientation Feedback')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('orientation_date', models.DateField(blank=True, null=True)),
                ('intended_start_time', models.TimeField(blank=True, null=True)),
                ('intended_end_time', models.TimeField(blank=True, null=True)),
                ('auto_close_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('public_token', models.CharField(default=apps.orientation_feedback.models.generate_orientation_feedback_token, editable=False, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, choices=[('MANUAL', 'Ended by facilitator'), ('AUTOMATIC', 'Automatic closing time reached')], max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('eligible_count_snapshot', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('question_snapshot_version', models.PositiveIntegerField(default=0, editable=False)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orientation_feedback_sessions', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientation_feedback_sessions', to='tenants.campus')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_orientation_feedback_sessions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_orientation_feedback_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orientation_feedback_sessions', to=settings.AUTH_USER_MODEL)),
                ('eligible_head_roles', models.ManyToManyField(blank=True, related_name='orientation_feedback_sessions', through='orientation_feedback.OrientationSurveyEligibleRole', to='rbac.role')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_orientation_feedback_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientation_feedback_sessions', to='tenants.tenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orientation_feedback_sessions', to='academics.term')),
            ],
            options={
                'db_table': 'orientation_feedback_sessions',
                'ordering': ['-orientation_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='orientationsurveyresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='orientation_feedback.orientationsurveysession'),
        ),
        migrations.AddField(
            model_name='orientationsurveyquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='orientation_feedback.orientationsurveysession'),
        ),
        migrations.AddField(
            model_name='orientationsurveyparticipation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='orientation_feedback.orientationsurveysession'),
        ),
        migrations.AddField(
            model_name='orientationsurveyeligiblerole',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_role_links', to='orientation_feedback.orientationsurveysession'),
        ),
        migrations.CreateModel(
            name='OrientationSurveyAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='orientation_feedback.orientationsurveyanswer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_selections', to='orientation_feedback.orientationsurveychoice')),
            ],
            options={
                'db_table': 'orientation_feedback_answer_choices',
                'constraints': [models.UniqueConstraint(fields=('answer', 'choice'), name='uq_orient_answer_choice')],
            },
        ),
        migrations.AddConstraint(
            model_name='orientationsurveychoice',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='uq_orient_question_choice'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveychoice',
            constraint=models.UniqueConstraint(fields=('question', 'display_order'), name='uq_orient_question_choice_order'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveychoice',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 1), ('score__lte', 5)), _connector='OR'), name='ck_orient_choice_score'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveyanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='uq_orient_response_question'),
        ),
        migrations.AddIndex(
            model_name='orientationsurveysession',
            index=models.Index(fields=['tenant', 'campus', 'status'], name='idx_orient_scope_status'),
        ),
        migrations.AddIndex(
            model_name='orientationsurveysession',
            index=models.Index(fields=['survey_type', 'orientation_date'], name='idx_orient_type_date'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveysession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='ck_orient_cancel_evidence'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveysession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'OPEN'), _negated=True), models.Q(('started_at__isnull', False), ('started_by__isnull', False)), _connector='OR'), name='ck_orient_open_evidence'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveyquestion',
            constraint=models.UniqueConstraint(fields=('session', 'code'), name='uq_orient_session_question'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveyquestion',
            constraint=models.UniqueConstraint(fields=('session', 'display_order'), name='uq_orient_session_question_order'),
        ),
        migrations.AddIndex(
            model_name='orientationsurveyparticipation',
            index=models.Index(fields=['session', 'submitted_at'], name='idx_orient_part_submit'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveyparticipation',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='uq_orient_session_user'),
        ),
        migrations.AddConstraint(
            model_name='orientationsurveyeligiblerole',
            constraint=models.UniqueConstraint(fields=('session', 'role'), name='uq_orient_session_role'),
        ),
    ]
