# Generated by Django 5.2.12 on 2026-03-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portal', models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty')], max_length=10)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'menu_groups',
                'ordering': ['portal', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('portal', 'code'), name='uq_menu_groups_portal_code')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portal', models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty')], max_length=10)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('route_name', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.menugroup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['menu_group', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitempermission_set', to='navigation.menuitem')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitempermission_set', to='rbac.permission')),
            ],
            options={
                'db_table': 'menu_item_permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('portal', 'code'), name='uq_menu_items_portal_code'),
        ),
        migrations.AddConstraint(
            model_name='menuitempermission',
            constraint=models.UniqueConstraint(fields=('menu_item', 'permission'), name='uq_menu_item_permissions'),
        ),
    ]
