# Generated by Django 5.2.12 on 2026-03-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
        ('rbac', '0002_alter_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='navigation.menugroup'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='navigation.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitempermission',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuitempermission_set', to='navigation.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitempermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuitempermission_set', to='rbac.permission'),
        ),
    ]
