# Generated by Django 5.2.12 on 2026-03-20 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_base_value', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_grading_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grading_templates',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_assignments', to='academics.course')),
                ('effective_from_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_assignments', to='academics.term')),
                ('grading_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='grading.gradingtemplate')),
            ],
            options={
                'db_table': 'course_template_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingTemplatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('weight_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='grading.gradingtemplate')),
            ],
            options={
                'db_table': 'grading_template_periods',
                'ordering': ['template', 'sequence_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradingTemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='grading.gradingtemplateperiod')),
            ],
            options={
                'db_table': 'grading_template_components',
                'ordering': ['template_period', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradingTemplateSubcomponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_attendance_component', models.BooleanField(default=False)),
                ('admin_locked', models.BooleanField(default=True)),
                ('template_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomponents', to='grading.gradingtemplatecomponent')),
            ],
            options={
                'db_table': 'grading_template_subcomponents',
                'ordering': ['template_component', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseBaseValueOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_value_overrides', to='academics.course')),
                ('effective_from_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_value_overrides', to='academics.term')),
            ],
            options={
                'db_table': 'course_base_value_overrides',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'effective_from_term'), name='uq_course_base_value_overrides')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradingtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_grading_templates_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='coursetemplateassignment',
            constraint=models.UniqueConstraint(fields=('course', 'grading_template', 'effective_from_term'), name='uq_course_template_assignments'),
        ),
        migrations.AddConstraint(
            model_name='gradingtemplateperiod',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uq_template_periods_template_code'),
        ),
        migrations.AddConstraint(
            model_name='gradingtemplatecomponent',
            constraint=models.UniqueConstraint(fields=('template_period', 'code'), name='uq_template_components_period_code'),
        ),
        migrations.AddConstraint(
            model_name='gradingtemplatesubcomponent',
            constraint=models.UniqueConstraint(fields=('template_component', 'code'), name='uq_template_subcomponents_component_code'),
        ),
    ]
