# Generated by Django 5.2.12 on 2026-03-20 04:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grading', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='tenants.campus')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grade_activities', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='academics.courseoffering')),
                ('template_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='grading.gradingtemplatecomponent')),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='grading.gradingtemplateperiod')),
                ('template_subcomponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='grading.gradingtemplatesubcomponent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_activities',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('computed_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='grading.gradeactivity')),
                ('encoded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_activity_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_scores', to='students.student')),
            ],
            options={
                'db_table': 'student_activity_scores',
                'ordering': ['student__last_name', 'student__first_name', 'student__student_no'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'student'), name='uq_student_activity_scores_activity_student')],
            },
        ),
        migrations.CreateModel(
            name='StudentFinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_final_grades', to='tenants.campus')),
                ('computed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_final_grades', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_final_grades', to='academics.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_grades', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_final_grades', to='tenants.tenant')),
            ],
            options={
                'db_table': 'student_final_grades',
                'ordering': ['student__last_name', 'student__first_name', 'student__student_no'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'student'), name='uq_student_final_grades_offering_student')],
            },
        ),
        migrations.CreateModel(
            name='StudentPeriodGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_standing_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exam_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_period_grades', to='tenants.campus')),
                ('computed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_period_grades', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_period_grades', to='academics.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_grades', to='students.student')),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_period_grades', to='grading.gradingtemplateperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_period_grades', to='tenants.tenant')),
            ],
            options={
                'db_table': 'student_period_grades',
                'ordering': ['student__last_name', 'student__first_name', 'student__student_no'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'template_period', 'student'), name='uq_student_period_grades_offering_period_student')],
            },
        ),
    ]
