# Generated by Django 5.2.12 on 2026-03-20 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grading', '0002_gradeactivity_studentactivityscore_studentfinalgrade_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REOPENED', 'Reopened')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('submission_snapshot_json', models.JSONField(blank=True, null=True)),
                ('template_snapshot_json', models.JSONField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submissions', to='tenants.campus')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submissions', to='academics.courseoffering')),
                ('reopened_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_grade_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_grade_submissions', to=settings.AUTH_USER_MODEL)),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submissions', to='grading.gradingtemplateperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submissions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_submissions',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'template_period'), name='uq_grade_submissions_offering_period')],
            },
        ),
        migrations.CreateModel(
            name='GradingPeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period_code', models.CharField(max_length=50)),
                ('scope_type', models.CharField(choices=[('CAMPUS', 'Campus'), ('COURSE', 'Course Offering')], default='CAMPUS', max_length=12)),
                ('is_locked', models.BooleanField(default=False)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_period_locks', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_period_locks', to='tenants.campus')),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_period_locks', to='academics.courseoffering')),
                ('locked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_locks_set', to=settings.AUTH_USER_MODEL)),
                ('reopened_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_locks_reopened', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_period_locks', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_period_locks', to='academics.term')),
            ],
            options={
                'db_table': 'grading_period_locks',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'campus', 'academic_year', 'term', 'period_code', 'scope_type', 'course_offering'), name='uq_grading_period_locks_scope')],
            },
        ),
    ]
