# Generated by Django 5.2.12 on 2026-03-20 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grading', '0003_gradesubmission_gradingperiodlock'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=16)),
                ('justification', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_requests', to='tenants.campus')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_requests', to='academics.courseoffering')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grade_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_requests', to='grading.gradingtemplateperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_correction_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeCorrectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='correction_attachments/%Y/%m/')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_grade_correction_attachments', to=settings.AUTH_USER_MODEL)),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grading.gradecorrectionrequest')),
            ],
            options={
                'db_table': 'grade_correction_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeCorrectionRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requested_action', models.CharField(choices=[('UPDATE_SCORE', 'Update Score'), ('UPDATE_ATTENDANCE', 'Update Attendance'), ('UPDATE_STATUS', 'Update Status')], default='UPDATE_SCORE', max_length=24)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grading.gradecorrectionrequest')),
                ('grade_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_items', to='grading.gradeactivity')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_items', to='students.student')),
            ],
            options={
                'db_table': 'grade_correction_request_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GradeCorrectionUnlockWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('correction_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_window', to='grading.gradecorrectionrequest')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_unlock_windows', to='academics.courseoffering')),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_unlock_windows', to='grading.gradingtemplateperiod')),
            ],
            options={
                'db_table': 'grade_correction_unlock_windows',
                'ordering': ['-created_at'],
            },
        ),
    ]
