# Generated by Django 5.2.12 on 2026-03-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_gradecorrectionrequest_gradecorrectionattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingTemplateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('admin_locked', models.BooleanField(default=True)),
                ('template_subcomponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='grading.gradingtemplatesubcomponent')),
            ],
            options={
                'db_table': 'grading_template_details',
                'ordering': ['template_subcomponent', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gradeactivity',
            name='template_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_activities', to='grading.gradingtemplatedetail'),
        ),
        migrations.AddConstraint(
            model_name='gradingtemplatedetail',
            constraint=models.UniqueConstraint(fields=('template_subcomponent', 'code'), name='uq_template_details_subcomponent_code'),
        ),
    ]
