# Generated by Django 5.2.12 on 2026-03-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grading', '0005_gradingtemplatedetail_gradeactivity_template_detail_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantGradingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_code', models.CharField(max_length=64)),
                ('profile_name', models.CharField(max_length=150)),
                ('default_base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_default', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_profiles', to='tenants.campus')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_profiles', to='academics.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_profiles', to='tenants.department')),
                ('effective_from_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_grading_profiles', to='academics.term')),
                ('grading_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_grading_profiles', to='grading.gradingtemplate')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_profiles', to='tenants.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_profiles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_grading_profiles',
                'ordering': ['tenant', 'priority', 'profile_code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'profile_code'), name='uq_tenant_grading_profiles_code')],
            },
        ),
    ]
