# Generated by Django 5.2.12 on 2026-03-20 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_published_templates_approved(apps, schema_editor):
    GradingTemplate = apps.get_model("grading", "GradingTemplate")
    GradingTemplate.objects.filter(is_published=True).update(approval_status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_tenantgradingprofile'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplate',
            name='approval_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='approval_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_grading_template_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='approval_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='approval_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grading_template_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_APPROVAL', 'For Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TemplateHotfixRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apply_mode', models.CharField(choices=[('FUTURE_ONLY', 'Future Only'), ('ACTIVE_NOT_SUBMITTED', 'Active Not Submitted'), ('SELECTED_OFFERINGS', 'Selected Offerings')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], default='PENDING', max_length=16)),
                ('justification', models.TextField()),
                ('selected_offering_ids_json', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('affected_offering_count', models.PositiveIntegerField(default=0)),
                ('recomputed_offering_count', models.PositiveIntegerField(default=0)),
                ('impact_snapshot_json', models.JSONField(blank=True, null=True)),
                ('applied_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_template_hotfixes', to=settings.AUTH_USER_MODEL)),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_template_hotfixes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_template_hotfixes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotfix_requests', to='grading.gradingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_hotfix_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'template_hotfix_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(set_published_templates_approved, migrations.RunPython.noop),
    ]
