# Generated by Django 5.2.12 on 2026-03-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_gradingtemplate_approval_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecorrectionattachment',
            name='correction_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='grading.gradecorrectionrequest'),
        ),
        migrations.AlterField(
            model_name='gradecorrectionrequestitem',
            name='correction_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='grading.gradecorrectionrequest'),
        ),
        migrations.AlterField(
            model_name='gradecorrectionunlockwindow',
            name='correction_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unlock_window', to='grading.gradecorrectionrequest'),
        ),
    ]
