# Generated by Django 5.2.12 on 2026-03-21 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_facultyassignment_campus_facultyassignment_tenant'),
        ('grading', '0008_alter_gradecorrectionattachment_correction_request_and_more'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubmissionReopenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('justification', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_reopen_requests', to='tenants.campus')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_reopen_requests', to='academics.courseoffering')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_reopen_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grade_submission_reopen_requests', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_requests', to='grading.gradesubmission')),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_reopen_requests', to='grading.gradingtemplateperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_reopen_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_submission_reopen_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
