# Generated by Django 5.2.12 on 2026-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_gradesubmissionreopenrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplatecomponent',
            name='score_input_mode',
            field=models.CharField(choices=[('RAW_BASE50', 'Raw Score (Base-50)'), ('DIRECT_PERCENTAGE', 'Direct Percentage')], default='RAW_BASE50', max_length=24),
        ),
        migrations.AddField(
            model_name='gradingtemplatedetail',
            name='score_input_mode',
            field=models.CharField(choices=[('INHERIT', 'Inherit Parent Rule'), ('RAW_BASE50', 'Raw Score (Base-50)'), ('DIRECT_PERCENTAGE', 'Direct Percentage')], default='INHERIT', max_length=24),
        ),
        migrations.AddField(
            model_name='gradingtemplatesubcomponent',
            name='score_input_mode',
            field=models.CharField(choices=[('INHERIT', 'Inherit Parent Rule'), ('RAW_BASE50', 'Raw Score (Base-50)'), ('DIRECT_PERCENTAGE', 'Direct Percentage')], default='INHERIT', max_length=24),
        ),
    ]
