# Generated by Django 5.2.12 on 2026-03-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_gradingtemplatecomponent_score_input_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgradingprofile',
            name='passing_grade_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
