# Generated by Django 5.2.12 on 2026-03-23 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0011_tenantgradingprofile_passing_grade_threshold'),
        ('rbac', '0003_seed_analytics_permissions'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='faculty_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_correction_requests', to='tenants.department'),
        ),
        migrations.CreateModel(
            name='CorrectionApprovalRouteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('route_mode', models.CharField(choices=[('DIRECT_TO_FINAL', 'Direct to Final Approver'), ('TWO_STEP', 'Step 1 then Final Approver')], default='DIRECT_TO_FINAL', max_length=20)),
                ('step1_requires_same_department', models.BooleanField(default=False, help_text='When enabled, approver must share the same default department as requesting faculty.')),
                ('final_requires_same_department', models.BooleanField(default=False, help_text='When enabled, final approver must share the same default department as requesting faculty.')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_department', models.ForeignKey(blank=True, help_text='Leave blank to use this as tenant default route.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_approval_routes', to='tenants.department')),
                ('final_role', models.ForeignKey(blank=True, help_text='Final approver role for TWO_STEP route mode.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_route_final_rules', to='rbac.role')),
                ('step1_role', models.ForeignKey(help_text='First approver role. For DIRECT_TO_FINAL, this is also the final approver.', on_delete=django.db.models.deletion.PROTECT, related_name='correction_route_step1_rules', to='rbac.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_approval_routes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'correction_approval_routes',
                'ordering': ['tenant__name', 'faculty_department__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='approval_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_correction_requests', to='grading.correctionapprovalrouterule'),
        ),
        migrations.CreateModel(
            name='GradeCorrectionApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveSmallIntegerField(default=1)),
                ('approver_label', models.CharField(max_length=150)),
                ('requires_same_department', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_approval_steps', to='rbac.role')),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='grading.gradecorrectionrequest')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grade_correction_approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_correction_approval_steps',
                'ordering': ['correction_request_id', 'step_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='correctionapprovalrouterule',
            constraint=models.UniqueConstraint(fields=('tenant', 'faculty_department'), name='uq_correction_routes_tenant_department'),
        ),
        migrations.AddConstraint(
            model_name='gradecorrectionapprovalstep',
            constraint=models.UniqueConstraint(fields=('correction_request', 'step_order'), name='uq_grade_correction_approval_steps_order'),
        ),
    ]
