# Generated by Django 5.2.12 on 2026-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_gradecorrectionrequest_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecorrectionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LAPSED', 'Lapsed'), ('CLOSED', 'Closed')], default='PENDING', max_length=16),
        ),
    ]
