# Generated by Django 5.2.12 on 2026-04-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0013_alter_gradecorrectionrequest_status'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingTemplateApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('current_step_no', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_grading_template_workflows', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflows', to='grading.gradingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_template_approval_workflows', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grading_template_approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingTemplateApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_no', models.PositiveIntegerField()),
                ('step_code', models.CharField(max_length=40)),
                ('step_label', models.CharField(max_length=120)),
                ('role_codes_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=16)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('acted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_grading_template_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='grading.gradingtemplateapprovalworkflow')),
            ],
            options={
                'db_table': 'grading_template_approval_steps',
                'ordering': ['workflow', 'step_no'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'step_no'), name='uq_template_approval_steps_workflow_step')],
            },
        ),
        migrations.CreateModel(
            name='TemplateHotfixWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_no', models.PositiveIntegerField()),
                ('step_code', models.CharField(max_length=40)),
                ('step_label', models.CharField(max_length=120)),
                ('role_codes_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=16)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('acted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_template_hotfix_steps', to=settings.AUTH_USER_MODEL)),
                ('hotfix_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='grading.templatehotfixrequest')),
            ],
            options={
                'db_table': 'template_hotfix_workflow_steps',
                'ordering': ['hotfix_request', 'step_no'],
                'constraints': [models.UniqueConstraint(fields=('hotfix_request', 'step_no'), name='uq_template_hotfix_steps_request_step')],
            },
        ),
    ]
