# Generated by Django 5.2.12 on 2026-04-08 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_tenanttermgradingperiod_activegradingperiodsetting_and_more'),
        ('grading', '0014_gradingtemplateapprovalworkflow_and_more'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFinalClearanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_no', models.CharField(max_length=64, unique=True)),
                ('verification_code', models.CharField(max_length=32, unique=True)),
                ('clearance_status', models.CharField(choices=[('CLEARED', 'Cleared'), ('NOT_CLEARED', 'Not Cleared')], max_length=16)),
                ('total_assigned_courses', models.PositiveIntegerField(default=0)),
                ('complete_courses', models.PositiveIntegerField(default=0)),
                ('incomplete_courses', models.PositiveIntegerField(default=0)),
                ('snapshot_json', models.JSONField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_final_clearance_reports', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_final_clearance_reports', to='tenants.campus')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_final_clearance_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_faculty_final_clearance_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_final_clearance_reports', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_final_clearance_reports', to='academics.term')),
            ],
            options={
                'db_table': 'faculty_final_clearance_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'campus', 'term', 'faculty_user'], name='idx_fac_clear_scope'), models.Index(fields=['reference_no'], name='idx_fac_clear_ref')],
            },
        ),
    ]
