# Generated by Django 5.2.12 on 2026-04-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0015_facultyfinalclearancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgradingprofile',
            name='final_grade_formula_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantgradingprofile',
            name='final_grade_formula_mode',
            field=models.CharField(choices=[('AVERAGE_ACTIVE_PERIODS', 'Average All Active Template Periods'), ('WEIGHTED_PERIODS', 'Weighted Selected Periods')], default='AVERAGE_ACTIVE_PERIODS', max_length=40),
        ),
    ]
