# Generated by Django 5.2.12 on 2026-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0016_tenantgradingprofile_final_grade_formula_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplate',
            name='passing_grade_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
