# Generated by Django 5.2.12 on 2026-04-21 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_tenanttermgradingperiod_activegradingperiodsetting_and_more'),
        ('grading', '0017_gradingtemplate_passing_grade_threshold'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingperiodlock',
            name='completion_grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GradeLateCompletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('LAPSED', 'Lapsed')], default='PENDING', max_length=16)),
                ('justification', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('access_start_at', models.DateTimeField(blank=True, null=True)),
                ('access_end_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_late_completion_requests', to='tenants.campus')),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_grade_late_completion_requests', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_late_completion_requests', to='academics.courseoffering')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_late_completion_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grade_late_completion_requests', to=settings.AUTH_USER_MODEL)),
                ('template_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_late_completion_requests', to='grading.gradingtemplateperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_late_completion_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grade_late_completion_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
