# Generated by Django 5.2.12 on 2026-04-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0018_gradingperiodlock_completion_grace_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingperiodlock',
            name='completion_grace_until',
        ),
        migrations.DeleteModel(
            name='GradeLateCompletionRequest',
        ),
    ]
