# Generated by Django 5.2.12 on 2026-04-23 13:12

from django.db import migrations, models


def seed_exam_component_flags(apps, schema_editor):
    component_model = apps.get_model("grading", "GradingTemplateComponent")
    for component in component_model.objects.all():
        label = f"{component.code or ''} {component.name or ''}".upper()
        if "EXAM" in label:
            component.is_exam_component = True
            component.save(update_fields=["is_exam_component"])


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0019_remove_gradingperiodlock_completion_grace_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplatecomponent',
            name='is_exam_component',
            field=models.BooleanField(default=False, help_text='Marks this major component as the period exam bucket for class-standing/exam summary separation.'),
        ),
        migrations.RunPython(seed_exam_component_flags, migrations.RunPython.noop),
    ]
