# Generated by Django 5.2.12 on 2026-04-25 09:32

import apps.core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0020_gradingtemplatecomponent_is_exam_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecorrectionattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gradecorrectionattachment',
            name='file_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradecorrectionattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradecorrectionattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.upload_paths.correction_attachment_upload_path),
        ),
    ]
