# Generated by Django 5.2.12 on 2026-04-25 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoffering_idx_offer_scope_status_and_more'),
        ('grading', '0021_gradecorrectionattachment_content_type_and_more'),
        ('students', '0003_update_student_uniqueness_scope'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gradeactivity',
            index=models.Index(fields=['offering', 'template_period', 'is_active'], name='idx_gradeact_off_period'),
        ),
        migrations.AddIndex(
            model_name='gradeactivity',
            index=models.Index(fields=['tenant', 'campus', 'is_active'], name='idx_gradeact_scope'),
        ),
        migrations.AddIndex(
            model_name='gradecorrectionrequest',
            index=models.Index(fields=['tenant', 'campus', 'status'], name='idx_correction_scope_status'),
        ),
        migrations.AddIndex(
            model_name='gradecorrectionrequest',
            index=models.Index(fields=['offering', 'template_period', 'status'], name='idx_correction_off_period'),
        ),
        migrations.AddIndex(
            model_name='gradecorrectionrequest',
            index=models.Index(fields=['requested_by_user', 'status'], name='idx_correction_requester'),
        ),
        migrations.AddIndex(
            model_name='gradesubmission',
            index=models.Index(fields=['tenant', 'campus', 'status'], name='idx_submission_scope_status'),
        ),
        migrations.AddIndex(
            model_name='gradesubmission',
            index=models.Index(fields=['offering', 'status', 'updated_at'], name='idx_submission_off_status'),
        ),
        migrations.AddIndex(
            model_name='gradesubmission',
            index=models.Index(fields=['template_period', 'status'], name='idx_submission_period_status'),
        ),
        migrations.AddIndex(
            model_name='gradesubmissionreopenrequest',
            index=models.Index(fields=['tenant', 'campus', 'status'], name='idx_reopen_scope_status'),
        ),
        migrations.AddIndex(
            model_name='gradesubmissionreopenrequest',
            index=models.Index(fields=['offering', 'template_period', 'status'], name='idx_reopen_off_period'),
        ),
        migrations.AddIndex(
            model_name='gradingperiodlock',
            index=models.Index(fields=['tenant', 'campus', 'term', 'is_active'], name='idx_locks_scope_term'),
        ),
        migrations.AddIndex(
            model_name='gradingperiodlock',
            index=models.Index(fields=['deadline_at', 'is_locked', 'is_active'], name='idx_locks_deadline'),
        ),
        migrations.AddIndex(
            model_name='studentactivityscore',
            index=models.Index(fields=['activity', 'is_active'], name='idx_scores_activity_active'),
        ),
        migrations.AddIndex(
            model_name='studentactivityscore',
            index=models.Index(fields=['student', 'is_active'], name='idx_scores_student_active'),
        ),
        migrations.AddIndex(
            model_name='studentfinalgrade',
            index=models.Index(fields=['tenant', 'campus', 'is_submitted'], name='idx_final_grade_scope_sub'),
        ),
        migrations.AddIndex(
            model_name='studentfinalgrade',
            index=models.Index(fields=['student', 'offering'], name='idx_final_grade_student'),
        ),
        migrations.AddIndex(
            model_name='studentperiodgrade',
            index=models.Index(fields=['tenant', 'campus', 'updated_at'], name='idx_period_grade_scope_upd'),
        ),
        migrations.AddIndex(
            model_name='studentperiodgrade',
            index=models.Index(fields=['offering', 'template_period', 'period_grade'], name='idx_period_grade_period'),
        ),
        migrations.AddIndex(
            model_name='studentperiodgrade',
            index=models.Index(fields=['student', 'offering'], name='idx_period_grade_student'),
        ),
    ]
