# Generated by Django 5.2.12 on 2026-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0022_gradeactivity_idx_gradeact_off_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgradingprofile',
            name='term_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('SUMMER', 'Summer'), ('SPECIAL', 'Special')], max_length=20, null=True),
        ),
    ]
