# Generated by Django 5.2.12 on 2026-05-02 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initiator(apps, schema_editor):
    GradeCorrectionRequest = apps.get_model("grading", "GradeCorrectionRequest")
    GradeCorrectionRequest.objects.filter(initiated_by_user__isnull=True).update(
        initiated_by_user_id=models.F("requested_by_user_id")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0023_tenantgradingprofile_term_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='initiated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_grade_correction_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='on_behalf_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='request_source',
            field=models.CharField(choices=[('FACULTY_SELF', 'Faculty Self'), ('ADMIN_ON_BEHALF', 'Admin On Behalf')], default='FACULTY_SELF', max_length=24),
        ),
        migrations.RunPython(backfill_initiator, migrations.RunPython.noop),
    ]
