# Generated by Django 5.2.12 on 2026-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0024_gradecorrectionrequest_initiated_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatehotfixrequest',
            name='apply_mode',
            field=models.CharField(choices=[('FUTURE_ONLY', 'Future Only'), ('ACTIVE_NOT_SUBMITTED', 'Active Not Submitted'), ('SELECTED_OFFERINGS', 'Selected Offerings'), ('REQUESTING_FACULTY_OFFERINGS', "Requesting Faculty's Accepted Offerings")], max_length=32),
        ),
    ]
