# Generated by Django 5.2.12 on 2026-05-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0026_tenantgradingprofile_period_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplatesubcomponent',
            name='detail_computation_mode',
            field=models.CharField(choices=[('WEIGHTED_DETAILS', 'Weighted Details'), ('AVERAGE_ACTIVITIES', 'Average Activities')], default='WEIGHTED_DETAILS', help_text='Controls how faculty-created activities under detail rows roll up into the subcomponent score.', max_length=24),
        ),
    ]
