# Generated by Django 5.2.12 on 2026-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0027_gradingtemplatesubcomponent_detail_computation_mode'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplate',
            name='department_visibility',
            field=models.CharField(choices=[('ALL', 'All Departments'), ('SELECTED', 'Selected Departments')], default='ALL', max_length=16),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='visible_departments',
            field=models.ManyToManyField(blank=True, related_name='visible_grading_templates', to='tenants.department'),
        ),
    ]
