# Generated by Django 5.2.12 on 2026-06-14 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_course_syllabus_url'),
        ('grading', '0028_gradingtemplate_department_visibility_and_more'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEncodingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_to_faculty', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_encoding_controls', to='academics.academicyear')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_encoding_controls', to='tenants.campus')),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_encoding_controls', to='academics.courseoffering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grade_encoding_controls', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_encoding_controls', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_encoding_controls', to='academics.term')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grade_encoding_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_encoding_controls',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'academic_year', 'term', 'is_active'], name='idx_enc_ctrl_scope_term'), models.Index(fields=['status', 'is_active'], name='idx_enc_ctrl_status'), models.Index(fields=['campus', 'course_offering'], name='idx_enc_ctrl_campus_course')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'academic_year', 'term', 'period_code', 'campus', 'course_offering'), name='uq_active_grade_encoding_control_scope')],
            },
        ),
    ]
