# Generated by Django 5.2.12 on 2026-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0029_gradeencodingcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplateperiod',
            name='grade_column_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
