# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


def backfill_ordered_route_steps(apps, schema_editor):
    CorrectionApprovalRouteRule = apps.get_model("grading", "CorrectionApprovalRouteRule")
    CorrectionApprovalRouteStep = apps.get_model("grading", "CorrectionApprovalRouteStep")

    for route in CorrectionApprovalRouteRule.objects.select_related("step1_role", "final_role").all():
        if not route.step1_role_id:
            continue
        if CorrectionApprovalRouteStep.objects.filter(route_rule_id=route.id).exists():
            continue

        CorrectionApprovalRouteStep.objects.create(
            route_rule_id=route.id,
            step_order=1,
            approver_role_id=route.step1_role_id,
            approver_label=route.step1_role.name or route.step1_role.code,
            requires_same_department=route.step1_requires_same_department,
            is_active=route.is_active,
        )
        if route.route_mode == "TWO_STEP" and route.final_role_id:
            CorrectionApprovalRouteStep.objects.create(
                route_rule_id=route.id,
                step_order=2,
                approver_role_id=route.final_role_id,
                approver_label=route.final_role.name or route.final_role.code,
                requires_same_department=route.final_requires_same_department,
                is_active=route.is_active,
            )


def remove_backfilled_ordered_route_steps(apps, schema_editor):
    CorrectionApprovalRouteStep = apps.get_model("grading", "CorrectionApprovalRouteStep")
    CorrectionApprovalRouteStep.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0030_gradingtemplateperiod_grade_column_label"),
        ("rbac", "0022_seed_user_role_assignment_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionApprovalRouteStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("step_order", models.PositiveSmallIntegerField(default=1)),
                ("approver_label", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "requires_same_department",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, approver must cover the requesting faculty department.",
                    ),
                ),
                (
                    "approver_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_route_ordered_steps",
                        to="rbac.role",
                    ),
                ),
                (
                    "route_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_steps",
                        to="grading.correctionapprovalrouterule",
                    ),
                ),
            ],
            options={
                "db_table": "correction_approval_route_steps",
                "ordering": ["route_rule_id", "step_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="correctionapprovalroutestep",
            constraint=models.UniqueConstraint(
                fields=("route_rule", "step_order"),
                name="uq_correction_route_steps_order",
            ),
        ),
        migrations.RunPython(backfill_ordered_route_steps, remove_backfilled_ordered_route_steps),
    ]
