# Generated by Django 5.2.12 on 2026-06-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_facultyassignmentreplacementlog'),
        ('grading', '0031_correctionapprovalroutestep'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionPetitionWindowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_mode', models.CharField(choices=[('OPEN_ANYTIME', 'Open Anytime'), ('DAYS_AFTER_PERIOD_END', 'Days After Period End'), ('CLOSED', 'Closed Manually')], default='OPEN_ANYTIME', max_length=32)),
                ('allowed_days_after_period_end', models.PositiveIntegerField(blank=True, null=True)),
                ('manual_notice', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_petition_policies', to='academics.academicyear')),
                ('campus', models.ForeignKey(blank=True, help_text='Leave blank to apply this policy tenant-wide.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_petition_policies', to='tenants.campus')),
                ('grading_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_petition_policies', to='grading.gradingtemplateperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_petition_policies', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_petition_policies', to='academics.term')),
            ],
            options={
                'db_table': 'correction_petition_window_policies',
                'ordering': ['tenant__name', 'campus__name', 'academic_year__code', 'term__code', 'grading_period__code', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('campus__isnull', True), ('is_active', True)), fields=('tenant', 'academic_year', 'term', 'grading_period'), name='uq_correction_petition_policy_tenant_scope'), models.UniqueConstraint(condition=models.Q(('campus__isnull', False), ('is_active', True)), fields=('tenant', 'campus', 'academic_year', 'term', 'grading_period'), name='uq_correction_petition_policy_campus_scope')],
            },
        ),
    ]
