# Generated by Django 5.2.12 on 2026-07-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0032_correctionpetitionwindowpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetemplateassignment',
            name='grading_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='grading.gradingtemplate'),
        ),
    ]
