# Generated by Codex for Correction Governance remediation.

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


CANONICAL_PERIOD_KEY_MAX_LENGTH = 120
ACTIVE_SCOPE_KEY_MAX_LENGTH = 64
ACTIVE_SCOPE_SERIALIZATION_VERSION = "correction-petition-policy-scope-v1"


def _canonical_period_key(value):
    raw = (value or "").strip().upper().replace("-", "").replace("_", "").replace(" ", "")
    standard_aliases = {
        "PRELIM": "PRELIM",
        "PRELIMEXAM": "PRELIM",
        "MIDTERM": "MIDTERM",
        "MIDTERMEXAM": "MIDTERM",
        "PREFINAL": "PREFINAL",
        "FINAL": "FINAL",
        "FINALEXAM": "FINAL",
    }
    return standard_aliases.get(raw, raw)


def _active_scope_source(policy, canonical_key):
    """Return the exact, unambiguous business-scope serialization."""
    return json.dumps(
        [
            ACTIVE_SCOPE_SERIALIZATION_VERSION,
            policy.tenant_id,
            policy.campus_id,
            policy.academic_year_id,
            policy.term_id,
            canonical_key,
        ],
        ensure_ascii=True,
        separators=(",", ":"),
    )


def _active_scope_key(policy, canonical_key):
    if not policy.is_active:
        return None
    source = _active_scope_source(policy, canonical_key)
    return hashlib.sha256(source.encode("utf-8")).hexdigest()


def preflight_legacy_policies(apps, schema_editor):
    """Validate all legacy data before this migration mutates schema."""
    Policy = apps.get_model("grading", "CorrectionPetitionWindowPolicy")
    active_scopes = {}
    for policy in Policy.objects.select_related("grading_period").order_by("id"):
        canonical_key = _canonical_period_key(policy.grading_period.code or policy.grading_period.name)
        if not canonical_key:
            raise RuntimeError(
                f"Correction petition policy {policy.pk} has no usable grading-period identity. "
                "Resolve it before applying migration 0034."
            )
        if len(canonical_key) > CANONICAL_PERIOD_KEY_MAX_LENGTH:
            raise RuntimeError(
                f"Correction petition policy {policy.pk} canonical grading-period identity exceeds "
                f"{CANONICAL_PERIOD_KEY_MAX_LENGTH} characters. Resolve it before applying migration 0034."
            )
        if not policy.is_active:
            continue
        scope_source = _active_scope_source(policy, canonical_key)
        active_scopes.setdefault(scope_source, []).append(policy.pk)
    conflicts = {key: ids for key, ids in active_scopes.items() if len(ids) > 1}
    if conflicts:
        details = "; ".join(f"{key}: policy IDs {ids}" for key, ids in sorted(conflicts.items()))
        raise RuntimeError(
            "Cannot apply migration 0034 because active correction petition policies collapse to the same "
            f"canonical scope. Resolve the conflicts before deployment: {details}"
        )


def backfill_policy_keys(apps, schema_editor):
    """Backfill the deterministic fields after the pre-DDL preflight.

    This operation intentionally contains no ordinary legacy-data validation
    branch after DDL.  Production deployment must quiesce all application and
    direct database writers from preflight through migration completion; this
    repository has no migration-aware write barrier to provide that guarantee.
    """
    Policy = apps.get_model("grading", "CorrectionPetitionWindowPolicy")
    updates = []
    for policy in Policy.objects.select_related("grading_period").order_by("id"):
        canonical_key = _canonical_period_key(policy.grading_period.code or policy.grading_period.name)
        policy.canonical_period_key = canonical_key
        policy.active_scope_key = _active_scope_key(policy, canonical_key)
        updates.append(policy)
    Policy.objects.bulk_update(updates, ["canonical_period_key", "active_scope_key"])


def irreversible_reverse(apps, schema_editor):
    raise IrreversibleError(
        "Migration 0034 is intentionally irreversible: broad correction petition policies cannot be represented "
        "by the prior non-null academic-year and term schema. Roll back with a forward-compatible database plan."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0033_alter_coursetemplateassignment_grading_template"),
    ]

    operations = [
        # This must remain first: a collision must fail before AddField or any
        # other DDL reaches MariaDB.
        migrations.RunPython(preflight_legacy_policies, migrations.RunPython.noop),
        migrations.AddField(
            model_name="correctionpetitionwindowpolicy",
            name="canonical_period_key",
            field=models.CharField(db_index=True, default="", max_length=CANONICAL_PERIOD_KEY_MAX_LENGTH),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correctionpetitionwindowpolicy",
            name="active_scope_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="MariaDB-enforced unique identity for an active correction petition policy scope.",
                max_length=ACTIVE_SCOPE_KEY_MAX_LENGTH,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="correctionpetitionwindowpolicy",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_petition_policies",
                to="academics.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="correctionpetitionwindowpolicy",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_petition_policies",
                to="academics.term",
            ),
        ),
        migrations.RunPython(backfill_policy_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="correctionpetitionwindowpolicy",
            name="canonical_period_key",
            field=models.CharField(
                db_index=True,
                help_text="Normalized logical period identity used for correction governance.",
                max_length=CANONICAL_PERIOD_KEY_MAX_LENGTH,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="correctionpetitionwindowpolicy",
            name="uq_correction_petition_policy_tenant_scope",
        ),
        migrations.RemoveConstraint(
            model_name="correctionpetitionwindowpolicy",
            name="uq_correction_petition_policy_campus_scope",
        ),
        migrations.AddConstraint(
            model_name="correctionpetitionwindowpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(term__isnull=True) | models.Q(academic_year__isnull=False),
                name="ck_corr_petition_term_requires_ay",
            ),
        ),
        # Last forward means reverse reaches this guard before any reverse DDL.
        migrations.RunPython(migrations.RunPython.noop, irreversible_reverse),
    ]
