# Generated by Django 5.2.12 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0002_auditlog_idx_audit_scope_created_and_more"),
        ("grading", "0034_correctionpetitionwindowpolicy_canonical_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeCorrectionApprovalAuthoritySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_order", models.PositiveSmallIntegerField()),
                ("configured_approver_role_code", models.CharField(max_length=64)),
                ("requires_same_department", models.BooleanField(default=False)),
                (
                    "authorization_type",
                    models.CharField(
                        choices=[
                            ("APPROVER_ROLE", "Configured approver role"),
                            ("SUPER_ADMIN_ROLE", "Super administrator role"),
                            ("SUPERUSER", "Django superuser"),
                        ],
                        max_length=24,
                    ),
                ),
                ("authority_role_code", models.CharField(blank=True, max_length=64, null=True)),
                ("authority_assignment_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("scope_covers_faculty_department", models.BooleanField(default=False)),
                ("decided_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_audit_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_approval_authority_snapshot",
                        to="auditlog.auditlog",
                    ),
                ),
                (
                    "approval_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_authority_snapshots",
                        to="grading.correctionapprovalrouterule",
                    ),
                ),
                (
                    "approval_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_snapshot",
                        to="grading.gradecorrectionapprovalstep",
                    ),
                ),
                (
                    "authority_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_correction_authority_snapshots",
                        to="rbac.userrole",
                    ),
                ),
                (
                    "authority_campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_grade_correction_snapshots",
                        to="tenants.campus",
                    ),
                ),
                (
                    "authority_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_grade_correction_snapshots",
                        to="tenants.department",
                    ),
                ),
                (
                    "authority_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_grade_correction_snapshots",
                        to="rbac.role",
                    ),
                ),
                (
                    "authority_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_grade_correction_snapshots",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_correction_authority_snapshots",
                        to="tenants.campus",
                    ),
                ),
                (
                    "configured_approver_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configured_grade_correction_authority_snapshots",
                        to="rbac.role",
                    ),
                ),
                (
                    "correction_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_authority_snapshots",
                        to="grading.gradecorrectionrequest",
                    ),
                ),
                (
                    "effective_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effective_grade_correction_authority_snapshots",
                        to="tenants.department",
                    ),
                ),
                (
                    "faculty_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_correction_authority_snapshots",
                        to="tenants.department",
                    ),
                ),
                (
                    "reviewer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_correction_authority_snapshots",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_correction_authority_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "grade_correction_approval_authority_snapshots",
                "ordering": ["correction_request_id", "step_order"],
            },
        ),
        migrations.AddIndex(
            model_name="gradecorrectionapprovalauthoritysnapshot",
            index=models.Index(
                fields=["correction_request", "step_order"],
                name="idx_corr_auth_request_step",
            ),
        ),
    ]
