# Generated by Django 5.2.12 on 2026-03-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_security_fields'),
        ('tenants', '0002_alter_systemsetting_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='tenants.department'),
        ),
    ]
