# Generated by Django 5.2.12 on 2026-04-05 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_default_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLoginLockoutState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('portal_code', models.CharField(choices=[('ADMIN', 'Admin Portal'), ('FACULTY', 'Faculty Portal')], max_length=20)),
                ('failed_attempt_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_lockout_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_login_lockout_states',
                'ordering': ['portal_code', 'username'],
                'indexes': [models.Index(fields=['portal_code', 'username'], name='portal_logi_portal__93f90c_idx'), models.Index(fields=['portal_code', 'locked_until'], name='portal_logi_portal__c94166_idx')],
                'constraints': [models.UniqueConstraint(fields=('username', 'portal_code'), name='uniq_portal_login_lockout_username_portal')],
            },
        ),
    ]
