# Generated by Django 5.2.12 on 2026-04-17 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_portalloginlockoutstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignatureCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_blob', models.BinaryField(blank=True, null=True)),
                ('encryption_nonce', models.BinaryField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_format', models.CharField(blank=True, max_length=20, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('content_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_signature_credentials', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_signature_credentials',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserSignatureUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('FINAL_CLEARANCE', 'Faculty Final Clearance'), ('CORRECTION_OFFICIAL_REPORT', 'Correction Official Report')], max_length=40)),
                ('document_reference', models.CharField(max_length=128)),
                ('usage_role', models.CharField(blank=True, max_length=100, null=True)),
                ('portal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_signature_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_signature_usage_logs',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['document_type', 'document_reference'], name='user_signat_documen_6a3daf_idx'), models.Index(fields=['user', 'used_at'], name='user_signat_user_id_9c7a9c_idx')],
            },
        ),
    ]
