# Generated by Django 5.2.12 on 2026-04-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginotpchallenge_user_faculty_quick_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeactivationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_user_deactivations', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_user_deactivations', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_user_deactivations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_deactivation_schedules',
                'ordering': ['scheduled_for', 'user__username'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='user_deacti_status_0eeab2_idx'), models.Index(fields=['user', 'status'], name='user_deacti_user_id_3fc9af_idx')],
            },
        ),
    ]
