# Generated by Django 5.2.12 on 2026-07-14 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantdataexportchallenge'),
        ('imports', '0006_importbatch_email_system_enabled_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('DISABLED_BY_SYSTEM', 'Disabled by System'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('ACCEPTED', 'Accepted')], default='NOT_REQUESTED', max_length=24)),
                ('version', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_successfully_sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faculty_invitations', to=settings.AUTH_USER_MODEL)),
                ('last_resend_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resent_faculty_invitations', to=settings.AUTH_USER_MODEL)),
                ('originating_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_invitations', to='imports.importbatchrow')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_invitations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idx_fac_inv_status_expiry'), models.Index(fields=['public_id'], name='idx_fac_inv_public_id')],
            },
        ),
    ]
