# Generated by Django 5.2.12 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_facultyinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersignatureusagelog",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("FINAL_CLEARANCE", "Faculty Final Clearance"),
                    ("CORRECTION_OFFICIAL_REPORT", "Correction Official Report"),
                    ("COMPLETE_TABULATION_SHEET", "Complete Tabulation Sheet"),
                ],
                max_length=40,
            ),
        ),
    ]
