# Generated by Django 5.2.12 on 2026-07-20 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_pre_registry_sessions(apps, schema_editor):
    Session = apps.get_model("sessions", "Session")
    Session.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usersignatureusagelog_document_type'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_portal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'active_portal_sessions',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='idx_act_sess_user_upd')],
            },
        ),
        migrations.RunPython(clear_pre_registry_sessions, migrations.RunPython.noop),
    ]
