# Generated by Django 5.2.12 on 2026-10-10 04:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiTizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('revision', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_archived', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.campus')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuiTizzQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prompt', models.TextField()),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('timer_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('quitizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quitizz.quitizz')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuiTizzSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('READY', 'Ready')], default='READY', max_length=16)),
                ('title_snapshot', models.CharField(max_length=200)),
                ('source_revision', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('scoring_policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('current_position', models.PositiveIntegerField(default=0)),
                ('state_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.campus')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='quitizz.quitizz')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuiTizzSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prompt', models.TextField()),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('timer_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quitizz.quitizzsession')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quitizz',
            index=models.Index(fields=['tenant', 'campus', 'owner', 'is_archived'], name='qt_owner_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='quitizz',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='qt_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzquestion',
            constraint=models.UniqueConstraint(fields=('quitizz', 'position'), name='qtq_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='quitizzquestion',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='qtq_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzquestion',
            constraint=models.CheckConstraint(condition=models.Q(('timer_seconds__gt', 0)), name='qtq_timer_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzquestion',
            constraint=models.CheckConstraint(condition=models.Q(('correct_choice__in', ['A', 'B', 'C', 'D'])), name='qtq_answer_ad'),
        ),
        migrations.AddConstraint(
            model_name='quitizzquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prompt', ''), _negated=True), models.Q(('choice_a', ''), _negated=True), models.Q(('choice_b', ''), _negated=True), models.Q(('choice_c', ''), _negated=True), models.Q(('choice_d', ''), _negated=True)), name='qtq_content_required'),
        ),
        migrations.AddIndex(
            model_name='quitizzsession',
            index=models.Index(fields=['tenant', 'campus', 'host', 'status'], name='qts_host_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(('source_revision__gt', 0), ('state_version__gt', 0)), name='qts_versions_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'READY')), name='qts_foundation_status'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='qtsq_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='qtsq_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(('timer_seconds__gt', 0)), name='qtsq_timer_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(('correct_choice__in', ['A', 'B', 'C', 'D'])), name='qtsq_answer_ad'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prompt', ''), _negated=True), models.Q(('choice_a', ''), _negated=True), models.Q(('choice_b', ''), _negated=True), models.Q(('choice_c', ''), _negated=True), models.Q(('choice_d', ''), _negated=True)), name='qtsq_content_required'),
        ),
    ]
