# Generated by Django 5.2.12 on 2026-10-10 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_question_public_ids(apps, schema_editor):
    questions = apps.get_model('quitizz', 'QuiTizzSessionQuestion').objects.using(schema_editor.connection.alias)
    while True:
        batch = list(questions.filter(public_id__isnull=True).order_by('pk')[:500])
        if not batch:
            break
        for question in batch:
            question.public_id = uuid.uuid4()
        questions.bulk_update(batch, ['public_id'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('quitizz', '0003_seed_faculty_navigation'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiTizzParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(max_length=32)),
                ('nickname_key', models.CharField(max_length=64)),
                ('reconnect_digest', models.CharField(editable=False, max_length=64)),
                ('reconnect_expires_at', models.DateTimeField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.PositiveBigIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('cumulative_response_ms', models.PositiveBigIntegerField(default=0)),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['joined_at', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='QuiTizzResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('received_at', models.DateTimeField()),
                ('elapsed_ms', models.PositiveBigIntegerField()),
                ('is_correct', models.BooleanField()),
                ('awarded_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='quitizzsession',
            name='qts_foundation_status',
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='join_generation',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='joining_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='public_id',
            field=models.UUIDField(null=True, editable=False, unique=True),
        ),
        migrations.RunPython(populate_question_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quitizzsessionquestion',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quitizzsession',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('LOBBY', 'Lobby'), ('QUESTION_OPEN', 'Question open'), ('QUESTION_CLOSED', 'Question closed'), ('ANSWER_REVEALED', 'Answer revealed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='READY', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['READY', 'LOBBY', 'QUESTION_OPEN', 'QUESTION_CLOSED', 'ANSWER_REVEALED', 'COMPLETED', 'CANCELLED'])), name='qts_gameplay_status'),
        ),
        migrations.AddField(
            model_name='quitizzparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='quitizz.quitizzsession'),
        ),
        migrations.AddField(
            model_name='quitizzresponse',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='quitizz.quitizzparticipant'),
        ),
        migrations.AddField(
            model_name='quitizzresponse',
            name='session_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='quitizz.quitizzsessionquestion'),
        ),
        migrations.AddIndex(
            model_name='quitizzparticipant',
            index=models.Index(fields=['session', 'removed_at', 'joined_at'], name='qtp_session_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='quitizzparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'nickname_key'), name='qtp_unique_nickname'),
        ),
        migrations.AddConstraint(
            model_name='quitizzparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nickname', ''), _negated=True), models.Q(('nickname_key', ''), _negated=True)), name='qtp_nickname_required'),
        ),
        migrations.AddConstraint(
            model_name='quitizzparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0), ('correct_count__gte', 0), ('cumulative_response_ms__gte', 0)), name='qtp_totals_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='quitizzparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('final_rank__isnull', True), ('final_rank__gt', 0), _connector='OR'), name='qtp_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='quitizzresponse',
            constraint=models.UniqueConstraint(fields=('participant', 'session_question'), name='qtr_one_response'),
        ),
        migrations.AddConstraint(
            model_name='quitizzresponse',
            constraint=models.CheckConstraint(condition=models.Q(('selected_choice__in', ['A', 'B', 'C', 'D'])), name='qtr_choice_ad'),
        ),
        migrations.AddConstraint(
            model_name='quitizzresponse',
            constraint=models.CheckConstraint(condition=models.Q(('elapsed_ms__gte', 0), ('awarded_points__gte', 0), ('awarded_points__lte', 1000)), name='qtr_score_bounds'),
        ),
    ]
