# Generated by Django 5.2.12 on 2026-10-11 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitizz', '0004_quitizzparticipant_quitizzresponse_and_more'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quitizzsession',
            name='automation_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='next_transition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='pause_reason',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='pause_remaining_us',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='phase_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='playback_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=16),
        ),
        migrations.AddField(
            model_name='quitizzsession',
            name='show_phase',
            field=models.CharField(choices=[('NONE', 'None'), ('ANSWERING', 'Answering'), ('SUSPENSE', 'Suspense'), ('RESULTS', 'Results'), ('PREPARING', 'Preparing'), ('FINISHED', 'Finished')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='active_elapsed_us',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quitizzsessionquestion',
            name='active_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='quitizzsession',
            index=models.Index(fields=['playback_mode', 'next_transition_at'], name='qts_auto_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(('playback_mode__in', ['MANUAL', 'AUTOMATIC'])), name='qts_playback_valid'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(('show_phase__in', ['NONE', 'ANSWERING', 'SUSPENSE', 'RESULTS', 'PREPARING', 'FINISHED'])), name='qts_phase_valid'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pause_reason', ''), ('pause_remaining_us__isnull', True), ('paused_at__isnull', True)), models.Q(('next_transition_at__isnull', True), ('pause_remaining_us__isnull', False), ('paused_at__isnull', False), models.Q(('pause_reason', ''), _negated=True)), _connector='OR'), name='qts_pause_consistent'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['COMPLETED', 'CANCELLED']), _negated=True), models.Q(('next_transition_at__isnull', True), ('paused_at__isnull', True)), _connector='OR'), name='qts_terminal_unscheduled'),
        ),
        migrations.AddConstraint(
            model_name='quitizzsession',
            constraint=models.CheckConstraint(condition=models.Q(('playback_mode', 'AUTOMATIC'), ('next_transition_at__isnull', True), _connector='OR'), name='qts_manual_unscheduled'),
        ),
    ]
