from django.urls import path

from . import (
    faculty_views,
    generation_readiness_views,
    monitoring_views,
    planning_readiness_views,
    reporting_views,
    stage6_views,
    views,
)

app_name = "departmental_exams"

urlpatterns = [
    path(
        "faculty/departmental-exams/resources/",
        faculty_views.resources_view,
        name="resources",
    ),
    path(
        "faculty/departmental-exams/resources/answer-sheet/",
        faculty_views.answer_sheet_view,
        name="answer_sheet",
    ),
    path(
        "faculty/departmental-exams/contributions/",
        faculty_views.contribution_list_view,
        name="contribution_list",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/",
        faculty_views.contribution_workspace_view,
        name="contribution_workspace",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questionnaires/<int:release_id>/set-<str:set_code>/print/",
        faculty_views.questionnaire_print_view,
        name="questionnaire_print",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questionnaires/<int:release_id>/personalized-sheets/",
        faculty_views.personalized_answer_sheet_overview_view,
        name="personalized_answer_sheet_overview",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questionnaires/<int:release_id>/personalized-sheets/offerings/<int:offering_id>/prepare/",
        faculty_views.personalized_answer_sheet_prepare_view,
        name="personalized_answer_sheet_prepare",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questionnaires/<int:release_id>/personalized-sheets/offerings/<int:offering_id>/<str:set_filter>/print/",
        faculty_views.personalized_answer_sheet_print_view,
        name="personalized_answer_sheet_print",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/answer-keys/<int:release_id>/set-<str:set_code>/",
        faculty_views.answer_key_view,
        name="faculty_answer_key",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/answer-keys/<int:release_id>/set-<str:set_code>/print/",
        faculty_views.answer_key_print_view,
        name="faculty_answer_key_print",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/answer-keys/<int:release_id>/set-<str:set_code>/checking-master/print/",
        faculty_views.checking_master_print_view,
        name="faculty_checking_master_print",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questions/add/",
        faculty_views.question_create_view,
        name="question_create",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questions/<int:question_id>/edit/",
        faculty_views.question_edit_view,
        name="question_edit",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questions/<int:question_id>/delete/",
        faculty_views.question_delete_view,
        name="question_delete",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/questions/reorder/",
        faculty_views.question_reorder_view,
        name="question_reorder",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/csv/template/",
        faculty_views.csv_template_view,
        name="csv_template",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/csv/upload/",
        faculty_views.csv_upload_view,
        name="csv_upload",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/docx/upload/",
        faculty_views.docx_upload_view,
        name="docx_upload",
    ),
    path(
        "faculty/departmental-exams/docx-imports/<uuid:token>/",
        faculty_views.docx_preview_view,
        name="docx_preview",
    ),
    path(
        "faculty/departmental-exams/docx-imports/<uuid:token>/rows/<int:row_number>/edit/",
        faculty_views.docx_row_edit_view,
        name="docx_row_edit",
    ),
    path(
        "faculty/departmental-exams/docx-imports/<uuid:token>/confirm/",
        faculty_views.docx_confirm_view,
        name="docx_confirm",
    ),
    path(
        "faculty/departmental-exams/docx-imports/<uuid:token>/status/",
        faculty_views.docx_status_view,
        name="docx_status",
    ),
    path(
        "faculty/departmental-exams/imports/<uuid:token>/",
        faculty_views.csv_preview_view,
        name="csv_preview",
    ),
    path(
        "faculty/departmental-exams/imports/<uuid:token>/errors.csv",
        faculty_views.csv_error_report_view,
        name="csv_error_report",
    ),
    path(
        "faculty/departmental-exams/imports/<uuid:token>/confirm/",
        faculty_views.csv_confirm_view,
        name="csv_confirm",
    ),
    path(
        "faculty/departmental-exams/imports/<uuid:token>/status/",
        faculty_views.csv_status_view,
        name="csv_status",
    ),
    path(
        "faculty/departmental-exams/contributions/<int:contribution_id>/submit/",
        faculty_views.contribution_submit_view,
        name="contribution_submit",
    ),
    path("admin-portal/departmental-exams/", views.cycle_list_view, name="cycle_list"),
    path(
        "admin-portal/departmental-exams/contributor-monitoring/",
        monitoring_views.contributor_monitoring_view,
        name="contributor_monitoring",
    ),
    path(
        "admin-portal/departmental-exams/contributor-monitoring/print/",
        monitoring_views.contributor_monitoring_print_view,
        name="contributor_monitoring_print",
    ),
    path(
        "admin-portal/departmental-exams/contributor-monitoring/automatic-generation-readiness/",
        generation_readiness_views.automatic_generation_readiness_view,
        name="automatic_generation_readiness",
    ),
    path(
        "admin-portal/departmental-exams/contributor-monitoring/automatic-generation-readiness/print/",
        generation_readiness_views.automatic_generation_readiness_print_view,
        name="automatic_generation_readiness_print",
    ),
    path(
        "admin-portal/departmental-exams/planning-readiness/",
        planning_readiness_views.planning_readiness_view,
        name="planning_readiness",
    ),
    path(
        "admin-portal/departmental-exams/planning-readiness/print/",
        planning_readiness_views.planning_readiness_print_view,
        name="planning_readiness_print",
    ),
    path(
        "admin-portal/departmental-exams/courses/<int:cycle_course_id>/roster/<str:action>/",
        monitoring_views.roster_action_view,
        name="roster_action",
    ),
    path("admin-portal/departmental-exams/cycles/create/", views.cycle_create_view, name="cycle_create"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/configuration/", views.cycle_configuration_view, name="cycle_configuration"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/configuration/apply-defaults/", views.cycle_apply_defaults_view, name="cycle_apply_defaults"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/prepare-faculty-contributions/", views.prepare_faculty_contributions_view, name="prepare_faculty_contributions"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/open/", views.cycle_open_view, name="cycle_open"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/close/", views.cycle_close_view, name="cycle_close"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/delete/", views.cycle_delete_view, name="cycle_delete"),
    path(
        "admin-portal/departmental-exams/assigned-courses/",
        views.assigned_course_examinations_view,
        name="assigned_course_examinations",
    ),
    path(
        "admin-portal/departmental-exams/assigned-courses/print/",
        views.assigned_courses_print_view,
        name="assigned_courses_print",
    ),
    path(
        "admin-portal/departmental-exams/assigned-courses/exempt/print/",
        views.exempt_courses_print_view,
        name="exempt_courses_print",
    ),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/courses/", views.cycle_course_list_view, name="cycle_course_list"),
    path("admin-portal/departmental-exams/automatic-summary/", stage6_views.automatic_generation_summary_entry_view, name="automatic_generation_summary_entry"),
    path("admin-portal/departmental-exams/cycles/<int:cycle_id>/automatic-summary/", stage6_views.automatic_generation_summary_view, name="automatic_generation_summary"),
    path("admin-portal/departmental-exams/questionnaire-print-release/", stage6_views.questionnaire_print_release_view, name="questionnaire_print_release"),
    path(
        "admin-portal/departmental-exams/answer-key-releases/<int:release_id>/viewers/",
        stage6_views.answer_key_viewers_view,
        name="answer_key_viewers",
    ),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/administration/", views.cycle_course_administration_view, name="cycle_course_administration"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/exempt/", views.cycle_course_exempt_view, name="cycle_course_exempt"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/restore/", views.cycle_course_restore_view, name="cycle_course_restore"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/configuration/", views.course_configuration_view, name="course_configuration"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/configuration/remove-overrides/", views.course_remove_overrides_view, name="course_remove_overrides"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/contribution/open/", views.course_contribution_open_view, name="course_contribution_open"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/contribution/close/", views.course_contribution_close_view, name="course_contribution_close"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/contribution/reopen/", views.course_contribution_reopen_view, name="course_contribution_reopen"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/contribution/automatic-reopen/", stage6_views.automatic_contribution_reopen_view, name="automatic_contribution_reopen"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/configuration/revert/", views.course_configuration_revert_view, name="course_configuration_revert"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/blueprint/", stage6_views.blueprint_configuration_view, name="blueprint_configuration"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/blueprint/review/", stage6_views.blueprint_review_view, name="blueprint_review"),
    path("admin-portal/departmental-exams/contributions/<int:contribution_id>/resolve-blocked/", stage6_views.blocked_contribution_resolve_view, name="blocked_contribution_resolve"),
    path("admin-portal/departmental-exams/questions/<int:question_id>/placement/", stage6_views.question_placement_view, name="question_placement"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/scenarios/save/", stage6_views.scenario_save_view, name="scenario_save"),
    path("admin-portal/departmental-exams/scenarios/<int:scenario_id>/delete/", stage6_views.scenario_delete_view, name="scenario_delete"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/generation/", stage6_views.generation_workspace_view, name="generation_workspace"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/generation/generate/", stage6_views.generate_exam_view, name="generate_exam"),
    path("admin-portal/departmental-exams/courses/<int:cycle_course_id>/generation/regenerate/", stage6_views.regenerate_exam_view, name="regenerate_exam"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/", stage6_views.generated_revision_detail_view, name="generated_revision_detail"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/selection-audit/", reporting_views.generation_selection_audit_view, name="generation_selection_audit"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/selection-audit/print/", reporting_views.generation_selection_audit_print_view, name="generation_selection_audit_print"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/answer-key/set-<str:set_code>/", reporting_views.generation_answer_key_view, name="generation_answer_key"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/answer-key/set-<str:set_code>/print/", reporting_views.generation_answer_key_print_view, name="generation_answer_key_print"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/questionnaire/set-<str:set_code>/print/", reporting_views.admin_questionnaire_print_view, name="admin_questionnaire_print"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/automatic-audits/<int:audit_run_id>/", reporting_views.automatic_generation_audit_result_view, name="automatic_generation_audit_result"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/automatic-audits/<int:audit_run_id>/print/", reporting_views.automatic_generation_audit_result_print_view, name="automatic_generation_audit_result_print"),
    path("admin-portal/departmental-exams/generations/<int:revision_id>/approve-lock/", stage6_views.approve_and_lock_view, name="approve_and_lock"),
]
