# Generated by Django 5.2.12 on 2026-07-14 12:24

import apps.exit_pulse.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0010_facultyassignmentreplacementlog'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitPulseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(max_length=200)),
                ('question_code', models.CharField(choices=[('UNDERSTANDING', 'How well do you understand today’s topic?'), ('APPLICATION_CONFIDENCE', 'How confident are you that you can apply today’s lesson?'), ('NEEDS_EXPLANATION', 'Does today’s topic need further explanation or examples?'), ('CUSTOM', 'Custom Question')], max_length=32)),
                ('question_text_snapshot', models.CharField(max_length=250)),
                ('custom_question', models.CharField(blank=True, max_length=250)),
                ('allow_written_feedback', models.BooleanField(default=False)),
                ('feedback_review_enabled', models.BooleanField(default=False)),
                ('feedback_review_prompt_snapshot', models.CharField(blank=True, max_length=200)),
                ('feedback_learned_enabled', models.BooleanField(default=False)),
                ('feedback_learned_prompt_snapshot', models.CharField(blank=True, max_length=200)),
                ('public_token', models.CharField(default=apps.exit_pulse.models.generate_exit_pulse_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('extended_at', models.DateTimeField(blank=True, null=True)),
                ('extension_count', models.PositiveSmallIntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='tenants.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='academics.course')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='academics.courseoffering')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exit_pulse_sessions', to=settings.AUTH_USER_MODEL)),
                ('faculty_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='academics.facultyassignment')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='academics.section')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_sessions', to='academics.term')),
            ],
            options={
                'db_table': 'exit_pulse_sessions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExitPulseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_code', models.CharField(choices=[('CONFIDENT', 'I understand it well and feel confident'), ('MOSTLY_UNDERSTOOD', 'I understand most of it'), ('NEEDS_CLARIFICATION', 'I need a little clarification'), ('NEEDS_PRACTICE', 'I need more examples or practice')], max_length=32)),
                ('feedback_review', models.CharField(blank=True, max_length=200)),
                ('feedback_learned', models.CharField(blank=True, max_length=200)),
                ('anonymous_token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('technical_identifier_expires_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exit_pulse.exitpulsesession')),
            ],
            options={
                'db_table': 'exit_pulse_responses',
                'ordering': ['submitted_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exitpulsesession',
            index=models.Index(fields=['faculty_user', 'status', 'created_at'], name='idx_pulse_fac_status'),
        ),
        migrations.AddIndex(
            model_name='exitpulsesession',
            index=models.Index(fields=['faculty_assignment', 'created_at'], name='idx_pulse_assignment'),
        ),
        migrations.AddIndex(
            model_name='exitpulsesession',
            index=models.Index(fields=['status', 'expires_at'], name='idx_pulse_status_exp'),
        ),
        migrations.AddIndex(
            model_name='exitpulsesession',
            index=models.Index(fields=['tenant', 'campus', 'created_at'], name='idx_pulse_scope_time'),
        ),
        migrations.AddConstraint(
            model_name='exitpulsesession',
            constraint=models.CheckConstraint(condition=models.Q(('extension_count__gte', 0), ('extension_count__lte', 1)), name='ck_pulse_extension_once'),
        ),
        migrations.AddIndex(
            model_name='exitpulseresponse',
            index=models.Index(fields=['session', 'response_code'], name='idx_pulse_resp_code'),
        ),
        migrations.AddIndex(
            model_name='exitpulseresponse',
            index=models.Index(fields=['technical_identifier_expires_at'], name='idx_pulse_ident_exp'),
        ),
        migrations.AddConstraint(
            model_name='exitpulseresponse',
            constraint=models.UniqueConstraint(fields=('session', 'anonymous_token_hash'), name='uq_pulse_response_browser'),
        ),
        migrations.AddConstraint(
            model_name='exitpulseresponse',
            constraint=models.CheckConstraint(condition=models.Q(('response_code__in', ['CONFIDENT', 'MOSTLY_UNDERSTOOD', 'NEEDS_CLARIFICATION', 'NEEDS_PRACTICE'])), name='ck_pulse_response_code'),
        ),
    ]
