# Generated by Django 5.2.12 on 2026-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_pulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpulsesession',
            name='enrollment_count_snapshot',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Eligible enrollment count captured when the session first starts; null for legacy sessions.', null=True),
        ),
    ]
