# Generated by Django 5.2.12 on 2026-07-15 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_classlistchangerequest_classlistchangerequestitem_and_more'),
        ('exit_pulse', '0002_exitpulsesession_enrollment_count_snapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exitpulseresponse',
            name='uq_pulse_response_browser',
        ),
        migrations.AddField(
            model_name='exitpulseresponse',
            name='privacy_notice_acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='exitpulseresponse',
            name='privacy_notice_version',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='exitpulseresponse',
            name='student_enrollment',
            field=models.ForeignKey(blank=True, editable=False, help_text='Validated class enrollment; null only for responses created before identity validation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_pulse_responses', to='enrollment.enrollment'),
        ),
        migrations.AddConstraint(
            model_name='exitpulseresponse',
            constraint=models.UniqueConstraint(fields=('session', 'student_enrollment'), name='uq_pulse_response_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='exitpulseresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('privacy_notice_acknowledged_at__isnull', True), ('privacy_notice_version', ''), ('student_enrollment__isnull', True)), models.Q(('privacy_notice_acknowledged_at__isnull', False), ('student_enrollment__isnull', False), models.Q(('privacy_notice_version', ''), _negated=True)), _connector='OR'), name='ck_pulse_response_identity_notice'),
        ),
    ]
