# Generated by Django 5.2.12 on 2026-03-20 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_years', to='tenants.tenant')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('default_base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='tenants.campus')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='tenants.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='tenants.tenant')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.CharField(blank=True, max_length=80, null=True)),
                ('schedule_text', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='tenants.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='tenants.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='tenants.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'course_offerings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to='academics.courseoffering')),
            ],
            options={
                'db_table': 'faculty_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('year_level', models.CharField(blank=True, max_length=50, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='tenants.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='tenants.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='tenants.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['campus', 'program', 'code'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.section'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academics.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='tenants.tenant')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['tenant', 'academic_year', 'sequence_no', 'name'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.term'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_academic_years_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_courses_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='facultyassignment',
            constraint=models.UniqueConstraint(fields=('offering', 'faculty_user'), name='uq_faculty_assignments_offering_user'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('tenant', 'campus', 'department', 'program', 'code'), name='uq_sections_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('tenant', 'academic_year', 'code'), name='uq_terms_tenant_ay_code'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('tenant', 'campus', 'department', 'term', 'course', 'section'), name='uq_offerings_scope_term_course_section'),
        ),
    ]
