# Generated by Django 5.2.12 on 2026-03-21 22:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_faculty_assignment_scope(apps, schema_editor):
    FacultyAssignment = apps.get_model("academics", "FacultyAssignment")
    for row in FacultyAssignment.objects.filter(tenant__isnull=True).select_related("offering").iterator():
        offering = row.offering
        if not offering:
            continue
        row.tenant_id = offering.tenant_id
        row.campus_id = offering.campus_id
        row.save(update_fields=["tenant", "campus"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0002_alter_systemsetting_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyassignment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to='tenants.campus'),
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_assignments', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_faculty_assignment_scope, migrations.RunPython.noop),
    ]
