# Generated by Django 5.2.12 on 2026-04-05 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_facultyassignment_reminder_fields'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTermGradingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_grading_periods', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_periods', to='academics.term')),
            ],
            options={
                'db_table': 'tenant_term_grading_periods',
                'ordering': ['tenant', 'term', 'sequence_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActiveGradingPeriodSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('auto_advanced_from_deadline', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_grading_period_settings', to='tenants.campus')),
                ('set_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_active_grading_periods', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_grading_period_settings', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_grading_period_settings', to='academics.term')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_settings', to='academics.tenanttermgradingperiod')),
            ],
            options={
                'db_table': 'active_grading_period_settings',
                'ordering': ['tenant', 'campus', 'term'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenanttermgradingperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'term', 'code'), name='uq_term_grading_periods_term_code'),
        ),
        migrations.AddConstraint(
            model_name='activegradingperiodsetting',
            constraint=models.UniqueConstraint(fields=('tenant', 'campus', 'term'), name='uq_active_grading_period_settings_scope'),
        ),
    ]
