# Generated by Django 5.2.12 on 2026-04-25 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_tenanttermgradingperiod_activegradingperiodsetting_and_more'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['tenant', 'campus', 'term', 'status', 'is_active'], name='idx_offer_scope_status'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['tenant', 'campus', 'department', 'term'], name='idx_offer_dept_term'),
        ),
        migrations.AddIndex(
            model_name='facultyassignment',
            index=models.Index(fields=['faculty_user', 'is_active', 'response_status'], name='idx_fac_assign_user_status'),
        ),
        migrations.AddIndex(
            model_name='facultyassignment',
            index=models.Index(fields=['tenant', 'campus', 'is_active'], name='idx_fac_assign_scope'),
        ),
    ]
