# Generated by Django 5.2.12 on 2026-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoffering_idx_offer_scope_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='term_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SUMMER', 'Summer'), ('SPECIAL', 'Special')], default='REGULAR', max_length=20),
        ),
    ]
