# Generated by Django 5.2.12 on 2026-07-11 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(choices=[('HAPPY', 'Happy'), ('NEUTRAL', 'Neutral'), ('SAD', 'Sad')], max_length=20)),
                ('suggestion', models.TextField(blank=True)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('route_name', models.CharField(blank=True, max_length=128)),
                ('feature_code', models.CharField(blank=True, max_length=80)),
                ('referrer_path', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('user_agent_summary', models.CharField(blank=True, max_length=160)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_feedback', to='tenants.campus')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_feedback', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_feedback',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idx_facfb_tenant_time'), models.Index(fields=['campus', 'created_at'], name='idx_facfb_campus_time'), models.Index(fields=['rating', 'created_at'], name='idx_facfb_rating_time'), models.Index(fields=['faculty_user', 'created_at'], name='idx_facfb_user_time'), models.Index(fields=['route_name', 'created_at'], name='idx_facfb_route_time')],
            },
        ),
    ]
