# Generated by Django 5.2.12 on 2026-03-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_no', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=16, null=True)),
                ('year_level', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenants.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenants.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenants.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenants.tenant')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name', 'student_no'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'student_no'), name='uq_students_tenant_student_no')],
            },
        ),
    ]
