# Generated by Django 5.2.12 on 2026-04-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_update_student_uniqueness_scope'),
        ('tenants', '0002_alter_systemsetting_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'campus', 'department', 'is_active', 'status'], name='idx_students_scope_status'),
        ),
    ]
