# Generated by Django 5.2.12 on 2026-04-25 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'campus', 'created_at'], name='idx_audit_scope_created'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user', 'portal', 'created_at'], name='idx_audit_actor_portal'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'action', 'created_at'], name='idx_audit_entity_action'),
        ),
    ]
