# Generated by Django 5.2.12 on 2026-07-18 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


APPROVED_REFERRAL_DESTINATIONS = {
    "GUIDANCE",
    "STUDENT_SERVICES",
    "ACADEMIC_HEAD",
    "OTHER_APPROVED",
}


def normalize_and_backfill(apps, schema_editor):
    Case = apps.get_model("interventions", "AcademicInterventionCase")
    Action = apps.get_model("interventions", "AcademicInterventionAction")
    Revision = apps.get_model("interventions", "AcademicInterventionDecisionRevision")

    for case in Case.objects.exclude(referral_destination="").iterator():
        original_destination = (case.referral_destination or "").strip()
        normalized = original_destination.upper().replace(" ", "_")
        if normalized not in APPROVED_REFERRAL_DESTINATIONS:
            case.referral_destination = "OTHER_APPROVED"
            case.referral_destination_label = original_destination[:120]
            case.save(update_fields=["referral_destination", "referral_destination_label", "updated_at"])

    duplicate_case_ids = (
        Action.objects.filter(status="PLANNED")
        .values_list("case_id", flat=True)
        .order_by()
        .distinct()
    )
    for case_id in duplicate_case_ids.iterator():
        planned_ids = list(
            Action.objects.filter(case_id=case_id, status="PLANNED")
            .order_by("-created_at", "-id")
            .values_list("id", flat=True)
        )
        if len(planned_ids) > 1:
            Action.objects.filter(id__in=planned_ids[1:]).update(
                status="CANCELLED",
                cancellation_reason="Superseded during one-active-planned-action integrity migration.",
            )

    for case in Case.objects.exclude(faculty_decision="").iterator():
        Revision.objects.get_or_create(
            case_id=case.id,
            revision_no=1,
            defaults={
                "decision": case.faculty_decision,
                "rationale": case.faculty_rationale,
                "decided_at": case.decision_at or case.updated_at or case.identified_at,
                "decided_by_id": case.updated_by_id or case.faculty_owner_id,
                "referral_destination": case.referral_destination,
                "referral_destination_label": case.referral_destination_label,
                "referral_date": case.referral_date,
                "referral_reason": case.referral_reason,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInterventionDecisionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_no', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('CONDUCT', 'Conduct Intervention'), ('MONITOR', 'Continue Monitoring'), ('NO_INTERVENTION', 'No Intervention Needed'), ('ALREADY_ADDRESSED', 'Already Addressed'), ('INSUFFICIENT_DATA', 'Insufficient Grading Data'), ('REFERRED', 'Referred to Another Office')], max_length=24)),
                ('rationale', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField()),
                ('correction_reason', models.CharField(blank=True, max_length=500)),
                ('referral_destination', models.CharField(blank=True, choices=[('GUIDANCE', 'Guidance Office'), ('STUDENT_SERVICES', 'Student Services'), ('ACADEMIC_HEAD', 'Academic Head'), ('OTHER_APPROVED', 'Other Approved Office')], max_length=32)),
                ('referral_destination_label', models.CharField(blank=True, max_length=120)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('referral_reason', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'academic_intervention_decision_revisions',
                'ordering': ['revision_no', 'id'],
            },
        ),
        migrations.AddField(
            model_name='academicinterventioncase',
            name='referral_destination_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academicinterventiondecisionrevision',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_revisions', to='interventions.academicinterventioncase'),
        ),
        migrations.AddField(
            model_name='academicinterventiondecisionrevision',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_intervention_decision_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicinterventiondecisionrevision',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='interventions.academicinterventiondecisionrevision'),
        ),
        migrations.AddIndex(
            model_name='academicinterventiondecisionrevision',
            index=models.Index(fields=['case', 'decided_at'], name='idx_aidr_case_decided'),
        ),
        migrations.AddConstraint(
            model_name='academicinterventiondecisionrevision',
            constraint=models.UniqueConstraint(fields=('case', 'revision_no'), name='uq_aidr_case_revision'),
        ),
        migrations.RunPython(normalize_and_backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='academicinterventioncase',
            name='referral_destination',
            field=models.CharField(blank=True, choices=[('GUIDANCE', 'Guidance Office'), ('STUDENT_SERVICES', 'Student Services'), ('ACADEMIC_HEAD', 'Academic Head'), ('OTHER_APPROVED', 'Other Approved Office')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='academicinterventionaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PLANNED')), fields=('case',), name='uq_aia_case_active_planned'),
        ),
    ]
