server {
    listen 80;
    server_name staging-grades.ncba.edu.ph;

    client_max_body_size 30M;

    location /static/ {
        alias /opt/edugradespro-staging/staticfiles/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location /media/ {
        alias /opt/edugradespro-staging/media/;
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/edugradespro-staging/gunicorn.sock;
        proxy_read_timeout 180;
    }
}
