# Generated by Django 5.2.12 on 2026-03-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.campus')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=128)),
                ('setting_value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_settings',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'setting_key'), name='uq_system_settings_tenant_key')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='tenants.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='tenants.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'campus', 'department', 'code'), name='uq_programs_scope_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'campus', 'code'), name='uq_departments_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_campuses_tenant_code'),
        ),
    ]
