# Generated by Codex on 2026-05-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_systemsetting_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="operation_branch",
            field=models.CharField(
                choices=[("ACADEMIC", "Academic"), ("ADMINISTRATIVE", "Administrative")],
                default="ACADEMIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="tenants.department",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="unit_type",
            field=models.CharField(
                choices=[("DIVISION", "Division"), ("AREA", "Area"), ("OFFICE", "Office"), ("OTHER", "Other")],
                default="AREA",
                max_length=20,
            ),
        ),
    ]
