# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_department_hierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("purpose", models.CharField(choices=[("SIS", "SIS Integration")], default="SIS", max_length=20)),
                ("key_prefix", models.CharField(max_length=32, unique=True)),
                ("key_hash", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tenant_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_keys",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_api_keys",
                "ordering": ["tenant__code", "purpose", "name"],
                "indexes": [
                    models.Index(fields=["key_prefix", "is_active"], name="idx_tapikey_prefix_active"),
                    models.Index(fields=["tenant", "purpose", "is_active"], name="idx_tapikey_tenant_purpose"),
                ],
            },
        ),
    ]
