# Generated by Django 5.2.12 on 2026-03-20 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DR', 'Dropped'), ('W', 'Withdrawn')], default='ACTIVE', max_length=16)),
                ('encoded_via_portal', models.CharField(choices=[('ADMIN', 'Admin Portal'), ('FACULTY', 'Faculty Portal')], default='ADMIN', max_length=16)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='tenants.campus')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.courseoffering')),
                ('encoded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.term')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['student__last_name', 'student__first_name', 'student__student_no'],
                'constraints': [models.UniqueConstraint(fields=('course_offering', 'student'), name='uq_enrollments_offering_student')],
            },
        ),
    ]
