# Generated by Django 5.2.12 on 2026-04-25 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoffering_idx_offer_scope_status_and_more'),
        ('enrollment', '0002_enrollment_status_drp_inc'),
        ('students', '0003_update_student_uniqueness_scope'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_offering', 'is_active', 'enrollment_status'], name='idx_enroll_offering_status'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'campus', 'academic_year', 'term', 'is_active'], name='idx_enroll_scope_term'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active', 'enrollment_status'], name='idx_enroll_student_status'),
        ),
    ]
