# Generated by Codex on 2026-06-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("enrollment", "0003_enrollment_idx_enroll_offering_status_and_more"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentAdjustmentLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("processed_at", models.DateTimeField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("completed_with_warning", "Completed with Warning"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("warning_flags", models.JSONField(blank=True, default=list)),
                ("impact_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "destination_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_enrollment_adjustment_logs",
                        to="academics.courseoffering",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_enrollment_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_enrollment_adjustment_logs",
                        to="academics.courseoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_adjustment_logs",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "enrollment_adjustment_logs",
                "ordering": ["-processed_at", "-id"],
                "indexes": [
                    models.Index(fields=["source_offering", "processed_at"], name="idx_enradj_source_time"),
                    models.Index(fields=["destination_offering", "processed_at"], name="idx_enradj_dest_time"),
                    models.Index(fields=["student", "processed_at"], name="idx_enradj_student_time"),
                    models.Index(fields=["result", "processed_at"], name="idx_enradj_result_time"),
                ],
            },
        ),
    ]
