# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0004_enrollmentadjustmentlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="batch_reference",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="destination_enrollment_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="destination_is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="destination_status",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="source_enrollment_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="source_previous_is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentadjustmentlog",
            name="source_previous_status",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name="enrollmentadjustmentlog",
            index=models.Index(fields=["batch_reference"], name="idx_enradj_batch_ref"),
        ),
    ]
