# Generated by Django 5.2.12 on 2026-06-21 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_facultyassignmentreplacementlog'),
        ('enrollment', '0005_enrollmentadjustmentlog_audit_state'),
        ('students', '0005_student_official_email'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassListChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('ADD', 'Add Student'), ('REMOVE', 'Remove Student')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_list_change_requests', to='tenants.campus')),
                ('faculty_requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_class_list_change_requests', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_list_change_requests', to='academics.courseoffering')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_class_list_change_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_list_change_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'class_list_change_requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassListChangeRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_student_no', models.CharField(blank=True, max_length=32)),
                ('reference_student_name', models.CharField(blank=True, max_length=150)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_list_change_request_items', to='enrollment.enrollment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.classlistchangerequest')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_list_change_request_items', to='students.student')),
            ],
            options={
                'db_table': 'class_list_change_request_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='classlistchangerequest',
            index=models.Index(fields=['campus', 'status', 'created_at'], name='idx_clsreq_campus_status'),
        ),
        migrations.AddIndex(
            model_name='classlistchangerequest',
            index=models.Index(fields=['offering', 'status', 'created_at'], name='idx_clsreq_offering_status'),
        ),
        migrations.AddIndex(
            model_name='classlistchangerequest',
            index=models.Index(fields=['faculty_requester', 'created_at'], name='idx_clsreq_requester_time'),
        ),
    ]
