# Generated by Django 5.2.12 on 2026-03-21 22:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_attendance_record_scope(apps, schema_editor):
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")
    for row in AttendanceRecord.objects.filter(tenant__isnull=True).select_related("session").iterator():
        session = row.session
        if not session:
            continue
        row.tenant_id = session.tenant_id
        row.campus_id = session.campus_id
        row.save(update_fields=["tenant", "campus"])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('tenants', '0002_alter_systemsetting_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='tenants.campus'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_attendance_record_scope, migrations.RunPython.noop),
    ]
