# Generated by Codex on 2026-03-23

from django.db import migrations


def seed_analytics_permissions(apps, schema_editor):
    Permission = apps.get_model("rbac", "Permission")
    permission_specs = [
        {
            "code": "grading_analytics.read",
            "module": "grading_analytics",
            "action": "read",
            "description": "Read admin grading analytics",
        },
        {
            "code": "faculty_analytics.read",
            "module": "faculty_analytics",
            "action": "read",
            "description": "Read faculty grading analytics",
        },
    ]
    for spec in permission_specs:
        Permission.objects.update_or_create(
            code=spec["code"],
            defaults={
                "module": spec["module"],
                "action": spec["action"],
                "description": spec["description"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_alter_rolepermission_permission_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_analytics_permissions, migrations.RunPython.noop),
    ]

