# Generated by Django 5.2.12 on 2026-03-31 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_seed_analytics_permissions'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='uq_user_roles_scoped',
        ),
        migrations.AddField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='tenants.department'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'tenant', 'campus', 'department'), name='uq_user_roles_scoped'),
        ),
    ]
