# Generated by Django 5.2.12 on 2026-06-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0021_seed_faculty_monitor_permissions'),
        ('rbac', '0022_seed_user_role_assignment_permission'),
    ]

    operations = [
    ]
