# Generated by Django 5.2.12 on 2026-09-24 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0011_course_exam_department'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverages', to='tenants.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_coverages', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverages', to='tenants.department')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverages', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverages', to='academics.courseoffering')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverages', to='academics.facultyassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_attendance_coverages',
                'ordering': ['offering_id', 'effective_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('course_code_snapshot', models.CharField(max_length=50)),
                ('course_title_snapshot', models.CharField(max_length=200)),
                ('section_code_snapshot', models.CharField(max_length=50)),
                ('section_name_snapshot', models.CharField(max_length=150)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_meeting_links', to='academics.courseoffering')),
            ],
            options={
                'db_table': 'faculty_attendance_meeting_offerings',
                'ordering': ['meeting_id', '-is_primary', 'offering_id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('original_text', models.CharField(blank=True, max_length=255)),
                ('interpretation_status', models.CharField(choices=[('CORRECTION_REQUIRED', 'Correction required'), ('CONFIRMED', 'Confirmed')], max_length=24)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='tenants.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_schedules', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='tenants.department')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedule_versions', to='academics.courseoffering')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_attendance_schedule_versions',
                'ordering': ['offering_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_text', models.CharField(blank=True, max_length=80)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('floor', models.CharField(blank=True, max_length=80)),
                ('room', models.CharField(blank=True, max_length=80)),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='faculty_attendance.scheduleversion')),
            ],
            options={
                'db_table': 'faculty_attendance_schedule_slots',
                'ordering': ['schedule_version_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TeachingMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('scheduled_minutes', models.PositiveIntegerField()),
                ('schedule_snapshot', models.JSONField(default=dict)),
                ('faculty_snapshot', models.JSONField(blank=True, default=dict)),
                ('location_snapshot', models.JSONField(default=dict)),
                ('sections_snapshot', models.JSONField(default=list)),
                ('unresolved_coverage', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_meetings', to='tenants.campus')),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='faculty_attendance.facultycoverage')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_meetings', to='tenants.department')),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_meetings', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_attendance_meetings', to=settings.AUTH_USER_MODEL)),
                ('offerings', models.ManyToManyField(related_name='attendance_meetings', through='faculty_attendance.MeetingOffering', to='academics.courseoffering')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='faculty_attendance.scheduleslot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_meetings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_attendance_meetings',
                'ordering': ['meeting_date', 'starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('decision_snapshot', models.JSONField(default=dict)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decided_attendance_substitutions', to=settings.AUTH_USER_MODEL)),
                ('original_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_substitutions_as_original', to=settings.AUTH_USER_MODEL)),
                ('substitute_faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_substitutions', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitution', to='faculty_attendance.teachingmeeting')),
            ],
            options={
                'db_table': 'faculty_attendance_substitutions',
            },
        ),
        migrations.CreateModel(
            name='MeetingReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('SCHEDULE', 'Schedule'), ('COVERAGE', 'Coverage')], max_length=16)),
                ('source_reference', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=12)),
                ('reason', models.TextField()),
                ('before_snapshot', models.JSONField(default=dict)),
                ('proposed_snapshot', models.JSONField(default=dict)),
                ('decision', models.CharField(blank=True, choices=[('KEEP_SNAPSHOT', 'Keep historical snapshot'), ('REVISE_FUTURE', 'Use change for future processing'), ('MANUAL_CORRECTION', 'Manual correction required')], max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('detected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detected_attendance_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_attendance_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='faculty_attendance.teachingmeeting')),
            ],
            options={
                'db_table': 'faculty_attendance_reconciliations',
                'ordering': ['status', 'meeting_id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='meetingoffering',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offering_links', to='faculty_attendance.teachingmeeting'),
        ),
        migrations.AddIndex(
            model_name='facultycoverage',
            index=models.Index(fields=['offering', 'effective_from', 'effective_until'], name='idx_att_cov_effective'),
        ),
        migrations.AddIndex(
            model_name='facultycoverage',
            index=models.Index(fields=['faculty_user', 'effective_from'], name='idx_att_cov_faculty'),
        ),
        migrations.AddConstraint(
            model_name='facultycoverage',
            constraint=models.UniqueConstraint(fields=('offering', 'faculty_user', 'effective_from'), name='uq_att_cov_offer_fac_start'),
        ),
        migrations.AddConstraint(
            model_name='facultycoverage',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='ck_att_cov_time_range'),
        ),
        migrations.AddIndex(
            model_name='scheduleversion',
            index=models.Index(fields=['tenant', 'campus', 'department', 'effective_from'], name='idx_att_sched_scope'),
        ),
        migrations.AddIndex(
            model_name='scheduleversion',
            index=models.Index(fields=['offering', 'effective_from', 'effective_until'], name='idx_att_sched_effective'),
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(fields=('offering', 'version_number'), name='uq_att_sched_offer_ver'),
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='ck_att_sched_date_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(fields=('schedule_version', 'sequence'), name='uq_att_sched_slot_seq'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(fields=('schedule_version', 'weekday', 'start_time', 'end_time'), name='uq_att_sched_slot_time'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ck_att_slot_time_order'),
        ),
        migrations.AddIndex(
            model_name='teachingmeeting',
            index=models.Index(fields=['tenant', 'campus', 'department', 'meeting_date'], name='idx_att_meeting_scope'),
        ),
        migrations.AddIndex(
            model_name='teachingmeeting',
            index=models.Index(fields=['faculty_user', 'meeting_date'], name='idx_att_meeting_faculty'),
        ),
        migrations.AddConstraint(
            model_name='teachingmeeting',
            constraint=models.UniqueConstraint(fields=('schedule_slot', 'meeting_date'), name='uq_att_meeting_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='teachingmeeting',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_att_meeting_time_order'),
        ),
        migrations.AddConstraint(
            model_name='teachingmeeting',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_minutes__gt', 0)), name='ck_att_meeting_minutes'),
        ),
        migrations.AddIndex(
            model_name='meetingreconciliation',
            index=models.Index(fields=['status', 'meeting'], name='idx_att_reconcile_status'),
        ),
        migrations.AddConstraint(
            model_name='meetingreconciliation',
            constraint=models.UniqueConstraint(fields=('meeting', 'source_type', 'source_reference'), name='uq_att_reconcile_source'),
        ),
        migrations.AddConstraint(
            model_name='meetingoffering',
            constraint=models.UniqueConstraint(fields=('meeting', 'offering'), name='uq_att_meeting_offering'),
        ),
    ]
