# Generated by Django 5.2.12 on 2026-09-24 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_exam_department'),
        ('faculty_attendance', '0002_seed_permissions'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_key', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('observed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_attendance_observations',
                'ordering': ['round_meeting_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PRESENT', 'Present'), ('EXCEPTION', 'Exception')], default='UNVERIFIED', max_length=12)),
                ('absent_without_notice_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('absent_with_notice_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('missed_periods', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('late_flag', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_flag', models.BooleanField(default=False)),
                ('early_minutes', models.PositiveIntegerField(default=0)),
                ('findings_snapshot', models.JSONField(blank=True, default=list)),
                ('correction_reason', models.TextField(blank=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_attendance_results', to=settings.AUTH_USER_MODEL)),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_attendance_results', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_result', to='faculty_attendance.teachingmeeting')),
                ('source_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_for_results', to='faculty_attendance.attendanceobservation')),
            ],
            options={
                'db_table': 'faculty_attendance_results',
            },
        ),
        migrations.CreateModel(
            name='AttendanceResultRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PRESENT', 'Present'), ('EXCEPTION', 'Exception')], max_length=12)),
                ('findings_snapshot', models.JSONField(blank=True, default=list)),
                ('change_reason', models.TextField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_result_changes', to=settings.AUTH_USER_MODEL)),
                ('faculty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_result_revisions', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='faculty_attendance.attendanceresult')),
                ('source_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_revisions', to='faculty_attendance.attendanceobservation')),
            ],
            options={
                'db_table': 'faculty_attendance_result_revisions',
                'ordering': ['result_id', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='CheckingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checking_date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('manifest_revision', models.PositiveIntegerField(default=1)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('manifest_frozen_at', models.DateTimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_checking_rounds', to='tenants.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_checking_rounds', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_checking_rounds', to='tenants.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_checking_rounds', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_attendance_checking_rounds',
                'ordering': ['-checking_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckingRoundMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('reviewed_result_revision', models.PositiveIntegerField(default=0)),
                ('meeting_snapshot', models.JSONField(default=dict)),
                ('checking_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_rows', to='faculty_attendance.checkinground')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checking_round_rows', to='faculty_attendance.teachingmeeting')),
            ],
            options={
                'db_table': 'faculty_attendance_checking_round_meetings',
                'ordering': ['checking_round_id', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='attendanceobservation',
            name='round_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='faculty_attendance.checkingroundmeeting'),
        ),
        migrations.CreateModel(
            name='CoverageReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ASSIGNMENT_CREATED', 'Assignment created'), ('ASSIGNMENT_REACTIVATED', 'Assignment reactivated'), ('ASSIGNMENT_ACCEPTED', 'Assignment accepted'), ('ASSIGNMENT_IMPORTED', 'Assignment imported'), ('PERMANENT_REPLACEMENT', 'Permanent replacement'), ('UNASSIGNMENT', 'Unassignment'), ('DIRECT_UPDATE', 'Direct assignment update')], max_length=32)),
                ('source_reference', models.CharField(max_length=96, unique=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=12)),
                ('reason', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_reconciliations', to='tenants.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_coverage_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_reconciliations', to='tenants.department')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_reconciliations', to='academics.courseoffering')),
                ('prior_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_changes_as_prior', to=settings.AUTH_USER_MODEL)),
                ('proposed_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_changes_as_proposed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_attendance_coverage_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_reconciliations', to='academics.facultyassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_reconciliations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_attendance_coverage_reconciliations',
                'ordering': ['status', 'offering_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceObservationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_type', models.CharField(choices=[('ABSENCE', 'Absence'), ('LATE', 'Late'), ('EARLY', 'Early dismissal')], max_length=12)),
                ('segment_key', models.CharField(max_length=40)),
                ('notice_status', models.CharField(blank=True, choices=[('A', 'Absent without notice'), ('N', 'Absent with notice')], max_length=1)),
                ('missed_periods', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('missed_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='faculty_attendance.attendanceobservation')),
            ],
            options={
                'db_table': 'faculty_attendance_observation_findings',
                'ordering': ['observation_id', 'finding_type', 'segment_key'],
                'constraints': [models.UniqueConstraint(fields=('observation', 'finding_type', 'segment_key'), name='uq_att_finding_segment'), models.CheckConstraint(condition=models.Q(('missed_periods__isnull', True), ('missed_periods__gte', 0), _connector='OR'), name='ck_att_finding_periods'), models.CheckConstraint(condition=models.Q(('missed_hours__isnull', True), ('missed_hours__gte', 0), _connector='OR'), name='ck_att_finding_hours')],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceresult',
            index=models.Index(fields=['faculty_user', 'status', 'meeting'], name='idx_att_result_faculty'),
        ),
        migrations.AddConstraint(
            model_name='attendanceresult',
            constraint=models.CheckConstraint(condition=models.Q(('absent_without_notice_hours__gte', 0)), name='ck_att_result_a_hours'),
        ),
        migrations.AddConstraint(
            model_name='attendanceresult',
            constraint=models.CheckConstraint(condition=models.Q(('absent_with_notice_hours__gte', 0)), name='ck_att_result_n_hours'),
        ),
        migrations.AddConstraint(
            model_name='attendanceresult',
            constraint=models.CheckConstraint(condition=models.Q(('missed_periods__gte', 0)), name='ck_att_result_periods'),
        ),
        migrations.AddConstraint(
            model_name='attendanceresultrevision',
            constraint=models.UniqueConstraint(fields=('result', 'revision'), name='uq_att_result_revision'),
        ),
        migrations.AddIndex(
            model_name='checkinground',
            index=models.Index(fields=['tenant', 'campus', 'department', 'checking_date'], name='idx_att_round_scope'),
        ),
        migrations.AddConstraint(
            model_name='checkingroundmeeting',
            constraint=models.UniqueConstraint(fields=('checking_round', 'meeting'), name='uq_att_round_meeting'),
        ),
        migrations.AddConstraint(
            model_name='checkingroundmeeting',
            constraint=models.UniqueConstraint(fields=('checking_round', 'sequence'), name='uq_att_round_sequence'),
        ),
        migrations.AddConstraint(
            model_name='attendanceobservation',
            constraint=models.UniqueConstraint(fields=('round_meeting', 'submission_key'), name='uq_att_observation_request'),
        ),
        migrations.AddIndex(
            model_name='coveragereconciliation',
            index=models.Index(fields=['offering', 'status', 'effective_at'], name='idx_att_covrec_offer'),
        ),
        migrations.AddIndex(
            model_name='coveragereconciliation',
            index=models.Index(fields=['tenant', 'campus', 'department', 'status'], name='idx_att_covrec_scope'),
        ),
    ]
