# Generated by Django 5.2.12 on 2026-09-24 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_attendance', '0004_seed_observation_permissions'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinground',
            name='checking_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinground',
            name='route_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='checkinground',
            name='route_revision_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedCheckerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_routes', to='tenants.campus')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_routes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_routes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_attendance_saved_routes',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checkinground',
            name='saved_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checking_rounds', to='faculty_attendance.savedcheckerroute'),
        ),
        migrations.CreateModel(
            name='SavedCheckerRouteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='faculty_attendance.savedcheckerroute')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_entries', to='faculty_attendance.scheduleslot')),
            ],
            options={
                'db_table': 'faculty_attendance_saved_route_entries',
                'ordering': ['route_id', 'position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='savedcheckerroute',
            index=models.Index(fields=['tenant', 'campus', 'owner', 'is_active'], name='idx_att_route_scope'),
        ),
        migrations.AddConstraint(
            model_name='savedcheckerroute',
            constraint=models.UniqueConstraint(fields=('tenant', 'campus', 'owner', 'name'), name='uq_att_route_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='savedcheckerrouteentry',
            constraint=models.UniqueConstraint(fields=('route', 'schedule_slot'), name='uq_att_route_slot'),
        ),
        migrations.AddConstraint(
            model_name='savedcheckerrouteentry',
            constraint=models.UniqueConstraint(fields=('route', 'position'), name='uq_att_route_position'),
        ),
    ]
