# Generated by Django 5.2.12 on 2026-10-01 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_exam_department'),
        ('faculty_attendance', '0011_seed_cutoff_publication_permission'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('kind', models.CharField(choices=[('ADMIN', 'Scheduled admin office hours'), ('LEAVE', 'Leave credit'), ('OTHER', 'Other deduction')], max_length=8)),
                ('leave_type', models.CharField(blank=True, choices=[('VL', 'Vacation leave'), ('SL', 'Sick leave'), ('EL', 'Emergency leave')], max_length=2)),
                ('offset_kind', models.CharField(blank=True, choices=[('A', 'Absent without notice'), ('N', 'Absent with notice'), ('L', 'Late'), ('E', 'Early dismissal'), ('OTHER', 'Other deduction')], max_length=8)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.TextField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dtr_adjustments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.department')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_revisions', to='faculty_attendance.dtradjustment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'db_table': 'faculty_attendance_dtr_adjustments',
                'indexes': [models.Index(fields=['tenant', 'campus', 'faculty_user', 'start_date', 'end_date'], name='idx_att_dtr_adj_scope')],
                'constraints': [models.UniqueConstraint(fields=('entry_key', 'revision'), name='uq_att_dtr_adjustment_rev'), models.CheckConstraint(condition=models.Q(('hours__gte', 0)), name='ck_att_dtr_adjustment_hours'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_att_dtr_adjustment_dates')],
            },
        ),
        migrations.CreateModel(
            name='FacultyDTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('review_fingerprint', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('finalization_reason', models.TextField()),
                ('finalized_at', models.DateTimeField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.campus')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_faculty_dtrs', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty_attendance.attendancecutoffpublication')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_revisions', to='faculty_attendance.facultydtr')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'db_table': 'faculty_attendance_final_dtrs',
                'indexes': [models.Index(fields=['tenant', 'campus', 'start_date', 'end_date'], name='idx_att_dtr_scope')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'campus', 'academic_year', 'term', 'start_date', 'end_date', 'faculty_user', 'revision'), name='uq_att_dtr_scope_rev'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_att_dtr_dates')],
            },
        ),
    ]
