# Generated by Django 5.2.12 on 2026-10-01 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_attendance', '0013_seed_dtr_permissions_navigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecutoffpublicationentry',
            name='status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PRESENT', 'Present'), ('EXCEPTION', 'Exception'), ('CLOSED', 'Class closed')], max_length=12),
        ),
        migrations.CreateModel(
            name='AttendanceClosureDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('CLOSED', 'Class closed'), ('REVOKED', 'Closure revoked')], max_length=8)),
                ('kind', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('SUSPENSION', 'Class suspension')], max_length=12)),
                ('pay_basis', models.CharField(choices=[('REGULAR', 'Regular faculty: scheduled hours paid'), ('PART_TIME', 'Part-time faculty: no-work hours unpaid')], max_length=10)),
                ('result_revision_at_decision', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_closure_decisions', to=settings.AUTH_USER_MODEL)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_decisions', to='faculty_attendance.teachingmeeting')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_revisions', to='faculty_attendance.attendanceclosuredecision')),
            ],
            options={
                'db_table': 'faculty_attendance_closure_decisions',
            },
        ),
        migrations.AddField(
            model_name='attendancecutoffpublicationentry',
            name='closure_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_entries', to='faculty_attendance.attendanceclosuredecision'),
        ),
        migrations.CreateModel(
            name='DTRMixedFindingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('intervals', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dtr_mixed_finding_decisions', to=settings.AUTH_USER_MODEL)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty_attendance.teachingmeeting')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty_attendance.attendancecutoffpublication')),
                ('result_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty_attendance.attendanceresultrevision')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_revisions', to='faculty_attendance.dtrmixedfindingdecision')),
            ],
            options={
                'db_table': 'faculty_attendance_dtr_mixed_decisions',
            },
        ),
        migrations.AddIndex(
            model_name='attendanceclosuredecision',
            index=models.Index(fields=['meeting', 'revision'], name='idx_att_closure_meeting_rev'),
        ),
        migrations.AddConstraint(
            model_name='attendanceclosuredecision',
            constraint=models.UniqueConstraint(fields=('meeting', 'revision'), name='uq_att_closure_meeting_rev'),
        ),
        migrations.AddIndex(
            model_name='dtrmixedfindingdecision',
            index=models.Index(fields=['publication', 'faculty_user'], name='idx_att_dtr_mixed_scope'),
        ),
        migrations.AddConstraint(
            model_name='dtrmixedfindingdecision',
            constraint=models.UniqueConstraint(fields=('publication', 'meeting', 'revision'), name='uq_att_dtr_mixed_rev'),
        ),
    ]
