# Generated by Django 5.2.12 on 2026-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_attendance', '0014_alter_attendancecutoffpublicationentry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceresultrevision',
            name='change_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dtradjustment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dtrmixedfindingdecision',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facultydtr',
            name='finalization_reason',
            field=models.TextField(blank=True),
        ),
    ]
