# Generated by Django 5.2.12 on 2026-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_attendance', '0015_alter_attendanceresultrevision_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceclosuredecision',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendancecutoffpublication',
            name='publication_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coveragereconciliation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facultycoverage',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingreconciliation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingsubstitution',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offeringattendancesourcechange',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recurringcombinedclass',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
