# Generated by Django 5.2.12 on 2026-10-02 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_attendance', '0018_attendancenoticemutex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCoverageAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('decision_snapshot', models.JSONField(default=dict)),
                ('adopted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decided_attendance_coverage_adoptions', to=settings.AUTH_USER_MODEL)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions', to='faculty_attendance.facultycoverage')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_coverage_adoptions', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_adoption', to='faculty_attendance.teachingmeeting')),
            ],
            options={
                'db_table': 'faculty_attendance_coverage_adoptions',
            },
        ),
    ]
