# Generated by Django 5.2.12 on 2026-10-04 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed(apps, schema_editor):
    Permission = apps.get_model('rbac', 'Permission')
    MenuGroup = apps.get_model('navigation', 'MenuGroup')
    MenuItem = apps.get_model('navigation', 'MenuItem')
    MenuItemPermission = apps.get_model('navigation', 'MenuItemPermission')
    permission, _ = Permission.objects.get_or_create(code='faculty_attendance.publish_faculty_cutoff', defaults={
        'module': 'faculty_attendance', 'action': 'publish_faculty_cutoff', 'is_active': True,
        'description': 'Publish complete immutable faculty attendance slices within authorized departments; no DTR finalization.'})
    group, _ = MenuGroup.objects.get_or_create(portal='ADMIN', code='FACULTY_ATTENDANCE', defaults={
        'label': 'Faculty Attendance', 'sort_order': 65, 'is_active': True})
    item, _ = MenuItem.objects.get_or_create(portal='ADMIN', code='ATTENDANCE_FACULTY_CUTOFF', defaults={
        'menu_group': group, 'label': 'Faculty Cutoff Processing', 'route_name': 'faculty_attendance:faculty_cutoff_review',
        'icon': 'bi bi-people', 'sort_order': 45, 'is_active': True})
    MenuItemPermission.objects.get_or_create(menu_item=item, permission=permission)
    # Deliberately no RolePermission/UserPermission grants.


def unseed(apps, schema_editor):
    Publication = apps.get_model('faculty_attendance', 'AttendanceCutoffPublication')
    if Publication.objects.filter(faculty_scope__isnull=False).exists():
        raise RuntimeError('Faculty publication history exists; do not reverse this migration or discard its scope.')
    MenuItem = apps.get_model('navigation', 'MenuItem')
    MenuItemPermission = apps.get_model('navigation', 'MenuItemPermission')
    item = MenuItem.objects.filter(portal='ADMIN', code='ATTENDANCE_FACULTY_CUTOFF').first()
    if item:
        MenuItemPermission.objects.filter(menu_item=item).delete()
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_exam_department'),
        ('faculty_attendance', '0019_meeting_coverage_adoption'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        ('rbac', '0036_seed_planning_readiness_permissions'),
        ('navigation', '0026_exam_workflow_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancecutoffpublication',
            name='uq_att_cutoff_scope_version',
        ),
        migrations.AddField(
            model_name='attendancecutoffpublication',
            name='faculty_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_cutoff_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecutoffpublication',
            name='scope_key',
            field=models.CharField(default='CAMPUS', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='attendancecutoffpublication',
            name='scope_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='attendancecutoffpublication',
            constraint=models.UniqueConstraint(fields=('tenant', 'campus', 'academic_year', 'term', 'start_date', 'end_date', 'scope_key', 'version'), name='uq_att_cutoff_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='attendancecutoffpublication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('faculty_scope__isnull', True), ('scope_key', 'CAMPUS')), models.Q(('faculty_scope__isnull', False), models.Q(('scope_key', 'CAMPUS'), _negated=True)), _connector='OR'), name='ck_att_cutoff_scope_kind'),
        ),
        migrations.RunPython(seed, unseed),
    ]
