from django.urls import path

from .api_views import sis_periodic_grades_api_view
from .academic_data_reconciliation import (
    academic_data_reconciliation_roster_view,
    academic_data_reconciliation_view,
)
from .import_views import (
    email_diagnostics_view,
    faculty_invitation_resend_view,
    import_batch_confirm_view,
    import_batch_detail_view,
    import_batch_error_report_view,
    import_batch_list_view,
    import_template_download_view,
    import_upload_view,
)
from .views import (
    academic_activity_consistency_view,
    academic_performance_insights_view,
    academic_performance_section_detail_view,
    academic_intervention_monitor_view,
    academic_intervention_monitor_detail_view,
    academic_year_create_view,
    academic_year_list_view,
    academic_year_update_view,
    actual_data_reset_view,
    active_academic_term_settings_view,
    active_grading_period_settings_view,
    configurable_features_settings_view,
    correction_governance_settings_view,
    document_print_settings_view,
    audit_log_detail_view,
    audit_log_list_view,
    recent_critical_actions_view,
    campus_create_view,
    campus_list_view,
    campus_update_view,
    course_create_view,
    course_list_view,
    course_update_view,
    course_base_override_create_view,
    course_base_override_list_view,
    course_base_override_update_view,
    course_template_assignment_create_view,
    course_template_assignment_list_view,
    course_template_assignment_update_view,
    dashboard_view,
    admin_guide_view,
    grading_setup_guide_view,
    grade_distribution_monitor_view,
    grade_submission_readiness_detail_view,
    grade_submission_readiness_view,
    grading_analytics_view,
    grade_prediction_monitor_view,
    department_create_view,
    department_list_view,
    department_update_view,
    enrollment_create_view,
    enrollment_adjustment_detail_view,
    enrollment_adjustment_offering_search_view,
    enrollment_adjustments_view,
    class_list_change_request_list_view,
    class_list_change_request_review_view,
    enrollment_list_view,
    enrollment_update_view,
    faculty_activity_monitor_view,
    faculty_feedback_dashboard_view,
    faculty_final_clearance_view,
    faculty_final_clearance_verify_view,
    faculty_user_invitation_send_view,
    faculty_deactivation_schedule_view,
    faculty_assignment_create_view,
    faculty_assignment_assign_view,
    faculty_assignment_dashboard_view,
    faculty_gradebook_explanation_view,
    faculty_gradebook_monitor_view,
    faculty_assignment_list_view,
    faculty_assignment_print_view,
    faculty_assignment_replace_view,
    faculty_assignment_renew_window_view,
    faculty_assignment_toggle_primary_view,
    faculty_assignment_unassign_view,
    faculty_assignment_update_view,
    grade_submission_list_view,
    grade_submission_reopen_view,
    grade_submission_reopen_request_list_view,
    grade_submission_reopen_request_review_view,
    grade_encoding_control_close_view,
    grade_encoding_control_create_view,
    grade_encoding_control_list_view,
    grade_encoding_control_open_view,
    grade_encoding_control_update_view,
    grade_correction_request_create_on_behalf_view,
    grade_correction_request_list_view,
    grade_correction_attachment_download_view,
    grade_correction_request_official_report_view,
    grade_correction_request_review_view,
    grading_template_create_view,
    grading_template_duplicate_view,
    grading_period_lock_close_view,
    grading_period_lock_create_view,
    grading_period_lock_list_view,
    grading_period_lock_reopen_view,
    grading_period_lock_update_view,
    grading_template_list_view,
    grading_template_review_approval_view,
    grading_template_publish_view,
    grading_template_submit_for_approval_view,
    grading_template_builder_view,
    grading_template_calculator_view,
    grading_template_structure_view,
    grading_template_update_view,
    inactive_record_delete_view,
    login_lockout_list_view,
    login_lockout_unlock_view,
    menu_group_create_view,
    menu_group_list_view,
    menu_group_update_view,
    menu_item_create_view,
    menu_item_list_view,
    menu_item_update_view,
    offering_create_view,
    offering_complete_tabulation_sheet_view,
    offering_list_view,
    offering_unassigned_print_view,
    offering_update_view,
    overdue_unsubmitted_report_view,
    program_create_view,
    program_list_view,
    program_update_view,
    role_create_view,
    role_delete_view,
    role_list_view,
    role_permission_compare_view,
    role_update_view,
    role_permissions_view,
    section_create_view,
    section_list_view,
    section_update_view,
    student_account_link_create_view,
    student_account_link_deactivate_view,
    student_account_link_list_view,
    student_account_provision_view,
    student_create_view,
    student_enrollment_query_view,
    student_list_view,
    student_update_view,
    tenant_create_view,
    tenant_data_export_view,
    tenant_grading_profile_create_view,
    tenant_grading_profile_duplicate_view,
    tenant_grading_profile_list_view,
    tenant_grading_profile_update_view,
    tenant_list_view,
    tenant_update_view,
    template_component_create_view,
    template_component_delete_view,
    template_component_list_view,
    template_component_update_view,
    template_detail_create_view,
    template_detail_list_view,
    template_detail_update_view,
    template_period_create_view,
    template_period_list_view,
    template_period_update_view,
    template_subcomponent_create_view,
    template_subcomponent_list_view,
    template_subcomponent_update_view,
    template_hotfix_create_view,
    template_hotfix_list_view,
    template_hotfix_review_view,
    term_create_view,
    term_list_view,
    template_governance_settings_view,
    term_update_view,
    admin_portal_root_view,
    user_create_view,
    user_change_password_view,
    user_list_view,
    user_privacy_consent_reset_view,
    user_roles_view,
    user_update_view,
)

app_name = "admin_portal"

urlpatterns = [
    path("admin-portal", admin_portal_root_view, name="root"),
    path("admin-portal/", admin_portal_root_view, name="root_slash"),
    path("api/v1/sis/periodic-grades/", sis_periodic_grades_api_view, name="sis_periodic_grades_api"),
    path("api/sis/periodic-grades/", sis_periodic_grades_api_view, name="sis_periodic_grades_api_alias"),
    path("admin-portal/dashboard/", dashboard_view, name="dashboard"),
    path(
        "admin-portal/academic-data-reconciliation/",
        academic_data_reconciliation_view,
        name="academic_data_reconciliation",
    ),
    path(
        "admin-portal/academic-data-reconciliation/offerings/<int:offering_id>/roster/",
        academic_data_reconciliation_roster_view,
        name="academic_data_reconciliation_roster",
    ),
    path("admin-portal/grading/analytics/", grading_analytics_view, name="grading_analytics"),
    path(
        "admin-portal/grading/performance-insights/",
        academic_performance_insights_view,
        name="academic_performance_insights",
    ),
    path(
        "admin-portal/grading/performance-insights/activity-consistency/",
        academic_activity_consistency_view,
        name="academic_activity_consistency",
    ),
    path(
        "admin-portal/grading/performance-insights/classes/<int:offering_id>/<str:period_code>/",
        academic_performance_section_detail_view,
        name="academic_performance_section_detail",
    ),
    path("admin-portal/interventions/", academic_intervention_monitor_view, name="academic_intervention_monitor"),
    path("admin-portal/interventions/<int:case_id>/", academic_intervention_monitor_detail_view, name="academic_intervention_monitor_detail"),
    path(
        "admin-portal/grading/grade-distribution-monitor/",
        grade_distribution_monitor_view,
        name="grade_distribution_monitor",
    ),
    path("admin-portal/guide/", admin_guide_view, name="guide"),
    path(
        "admin-portal/guide/grading-template-setup/",
        grading_setup_guide_view,
        name="grading_setup_guide",
    ),
    path(
        "admin-portal/tools/template-governance/",
        template_governance_settings_view,
        name="template_governance_settings",
    ),
    path(
        "admin-portal/tools/tenant-data-export/",
        tenant_data_export_view,
        name="tenant_data_export",
    ),
    path(
        "admin-portal/tools/faculty-feedback/",
        faculty_feedback_dashboard_view,
        name="faculty_feedback",
    ),
    path(
        "admin-portal/maintenance/inactive/<str:model_key>/<int:object_id>/delete/",
        inactive_record_delete_view,
        name="inactive_record_delete",
    ),
    path("admin-portal/organization/tenants/", tenant_list_view, name="tenant_list"),
    path("admin-portal/organization/tenants/create/", tenant_create_view, name="tenant_create"),
    path("admin-portal/organization/tenants/<int:tenant_id>/edit/", tenant_update_view, name="tenant_update"),
    path("admin-portal/organization/campuses/", campus_list_view, name="campus_list"),
    path("admin-portal/organization/campuses/create/", campus_create_view, name="campus_create"),
    path("admin-portal/organization/campuses/<int:campus_id>/edit/", campus_update_view, name="campus_update"),
    path("admin-portal/organization/departments/", department_list_view, name="department_list"),
    path(
        "admin-portal/organization/departments/create/",
        department_create_view,
        name="department_create",
    ),
    path(
        "admin-portal/organization/departments/<int:department_id>/edit/",
        department_update_view,
        name="department_update",
    ),
    path("admin-portal/organization/programs/", program_list_view, name="program_list"),
    path("admin-portal/organization/programs/create/", program_create_view, name="program_create"),
    path("admin-portal/organization/programs/<int:program_id>/edit/", program_update_view, name="program_update"),
    path("admin-portal/security/users/", user_list_view, name="user_list"),
    path(
        "admin-portal/security/faculty-deactivation/",
        faculty_deactivation_schedule_view,
        name="faculty_deactivation_schedule",
    ),
    path("admin-portal/security/login-lockouts/", login_lockout_list_view, name="login_lockout_list"),
    path(
        "admin-portal/security/login-lockouts/<int:lockout_id>/unlock/",
        login_lockout_unlock_view,
        name="login_lockout_unlock",
    ),
    path("admin-portal/security/users/create/", user_create_view, name="user_create"),
    path("admin-portal/security/users/<int:user_id>/edit/", user_update_view, name="user_update"),
    path(
        "admin-portal/security/users/<int:user_id>/faculty-invitation/send/",
        faculty_user_invitation_send_view,
        name="faculty_user_invitation_send",
    ),
    path(
        "admin-portal/security/users/<int:user_id>/change-password/",
        user_change_password_view,
        name="user_change_password",
    ),
    path(
        "admin-portal/security/users/<int:user_id>/privacy-consent/reset/",
        user_privacy_consent_reset_view,
        name="user_privacy_consent_reset",
    ),
    path("admin-portal/security/users/<int:user_id>/roles/", user_roles_view, name="user_roles"),
    path("admin-portal/security/roles/", role_list_view, name="role_list"),
    path("admin-portal/security/roles/compare/", role_permission_compare_view, name="role_permission_compare"),
    path("admin-portal/security/roles/create/", role_create_view, name="role_create"),
    path("admin-portal/security/roles/<int:role_id>/edit/", role_update_view, name="role_update"),
    path("admin-portal/security/roles/<int:role_id>/delete/", role_delete_view, name="role_delete"),
    path("admin-portal/security/roles/<int:role_id>/permissions/", role_permissions_view, name="role_permissions"),
    path("admin-portal/navigation/menu-groups/", menu_group_list_view, name="menu_group_list"),
    path("admin-portal/navigation/menu-groups/create/", menu_group_create_view, name="menu_group_create"),
    path(
        "admin-portal/navigation/menu-groups/<int:group_id>/edit/",
        menu_group_update_view,
        name="menu_group_update",
    ),
    path("admin-portal/navigation/menu-items/", menu_item_list_view, name="menu_item_list"),
    path("admin-portal/navigation/menu-items/create/", menu_item_create_view, name="menu_item_create"),
    path(
        "admin-portal/navigation/menu-items/<int:item_id>/edit/",
        menu_item_update_view,
        name="menu_item_update",
    ),
    path("admin-portal/audit/logs/", audit_log_list_view, name="audit_log_list"),
    path("admin-portal/audit/logs/<int:log_id>/", audit_log_detail_view, name="audit_log_detail"),
    path("admin-portal/audit/recent-critical-actions/", recent_critical_actions_view, name="recent_critical_actions"),
    path("admin-portal/academics/academic-years/", academic_year_list_view, name="academic_year_list"),
    path("admin-portal/academics/academic-years/create/", academic_year_create_view, name="academic_year_create"),
    path("admin-portal/academics/academic-years/<int:ay_id>/edit/", academic_year_update_view, name="academic_year_update"),
    path("admin-portal/academics/terms/", term_list_view, name="term_list"),
    path("admin-portal/academics/terms/create/", term_create_view, name="term_create"),
    path("admin-portal/academics/terms/<int:term_id>/edit/", term_update_view, name="term_update"),
    path("admin-portal/academics/courses/", course_list_view, name="course_list"),
    path("admin-portal/academics/courses/create/", course_create_view, name="course_create"),
    path("admin-portal/academics/courses/<int:course_id>/edit/", course_update_view, name="course_update"),
    path("admin-portal/academics/sections/", section_list_view, name="section_list"),
    path("admin-portal/academics/sections/create/", section_create_view, name="section_create"),
    path("admin-portal/academics/sections/<int:section_id>/edit/", section_update_view, name="section_update"),
    path("admin-portal/academics/offerings/", offering_list_view, name="offering_list"),
    path(
        "admin-portal/academics/offerings/print-unassigned/",
        offering_unassigned_print_view,
        name="offering_unassigned_print",
    ),
    path(
        "admin-portal/academics/offerings/<int:offering_id>/complete-tabulation/",
        offering_complete_tabulation_sheet_view,
        name="offering_complete_tabulation_sheet",
    ),
    path("admin-portal/academics/offerings/create/", offering_create_view, name="offering_create"),
    path("admin-portal/academics/offerings/<int:offering_id>/edit/", offering_update_view, name="offering_update"),
    path(
        "admin-portal/academics/faculty-assignments/",
        faculty_assignment_list_view,
        name="faculty_assignment_list",
    ),
    path(
        "admin-portal/academics/faculty-assignments/print/",
        faculty_assignment_print_view,
        name="faculty_assignment_print",
    ),
    path(
        "admin-portal/academics/faculty-assignments/dashboard/",
        faculty_assignment_dashboard_view,
        name="faculty_assignment_dashboard",
    ),
    path(
        "admin-portal/academics/faculty-gradebook/",
        faculty_gradebook_monitor_view,
        name="faculty_gradebook_monitor",
    ),
    path(
        "admin-portal/academics/faculty-gradebook/explain/<int:offering_id>/<int:period_id>/<int:student_id>/<str:grade_type>/",
        faculty_gradebook_explanation_view,
        name="faculty_gradebook_explanation",
    ),
    path(
        "admin-portal/academics/faculty-activity-monitor/",
        faculty_activity_monitor_view,
        name="faculty_activity_monitor",
    ),
    path(
        "admin-portal/grading/submission-readiness/",
        grade_submission_readiness_view,
        name="grade_submission_readiness",
    ),
    path(
        "admin-portal/grading/submission-readiness/<int:offering_id>/",
        grade_submission_readiness_detail_view,
        name="grade_submission_readiness_detail",
    ),
    path(
        "admin-portal/academics/faculty-final-clearance/",
        faculty_final_clearance_view,
        name="faculty_final_clearance",
    ),
    path(
        "admin-portal/academics/faculty-final-clearance/<int:report_id>/verify/",
        faculty_final_clearance_verify_view,
        name="faculty_final_clearance_verify",
    ),
    path(
        "admin-portal/academics/grade-predictions/",
        grade_prediction_monitor_view,
        name="grade_prediction_monitor",
    ),
    path(
        "admin-portal/academics/faculty-assignments/create/",
        faculty_assignment_create_view,
        name="faculty_assignment_create",
    ),
    path(
        "admin-portal/academics/faculty-assignments/assign/",
        faculty_assignment_assign_view,
        name="faculty_assignment_assign",
    ),
    path(
        "admin-portal/academics/faculty-assignments/unassign/",
        faculty_assignment_unassign_view,
        name="faculty_assignment_unassign",
    ),
    path(
        "admin-portal/academics/faculty-assignments/replace/",
        faculty_assignment_replace_view,
        name="faculty_assignment_replace",
    ),
    path(
        "admin-portal/academics/faculty-assignments/toggle-primary/",
        faculty_assignment_toggle_primary_view,
        name="faculty_assignment_toggle_primary",
    ),
    path(
        "admin-portal/academics/faculty-assignments/<int:assignment_id>/renew-window/",
        faculty_assignment_renew_window_view,
        name="faculty_assignment_renew_window",
    ),
    path(
        "admin-portal/academics/faculty-assignments/<int:assignment_id>/edit/",
        faculty_assignment_update_view,
        name="faculty_assignment_update",
    ),
    path("admin-portal/students/", student_list_view, name="student_list"),
    path(
        "admin-portal/students/enrollment-query/",
        student_enrollment_query_view,
        name="student_enrollment_query",
    ),
    path("admin-portal/students/account-links/", student_account_link_list_view, name="student_account_link_list"),
    path(
        "admin-portal/students/account-links/create/",
        student_account_link_create_view,
        name="student_account_link_create",
    ),
    path(
        "admin-portal/students/account-links/provision/",
        student_account_provision_view,
        name="student_account_provision",
    ),
    path(
        "admin-portal/students/account-links/<int:link_id>/deactivate/",
        student_account_link_deactivate_view,
        name="student_account_link_deactivate",
    ),
    path("admin-portal/students/create/", student_create_view, name="student_create"),
    path("admin-portal/students/<int:student_id>/edit/", student_update_view, name="student_update"),
    path("admin-portal/enrollment/", enrollment_list_view, name="enrollment_list"),
    path("admin-portal/enrollment/class-list-change-requests/", class_list_change_request_list_view, name="class_list_change_request_list"),
    path(
        "admin-portal/enrollment/class-list-change-requests/<int:request_id>/review/",
        class_list_change_request_review_view,
        name="class_list_change_request_review",
    ),
    path("admin-portal/enrollment/adjustments/", enrollment_adjustments_view, name="enrollment_adjustments"),
    path(
        "admin-portal/enrollment/adjustments/offerings/",
        enrollment_adjustment_offering_search_view,
        name="enrollment_adjustment_offering_search",
    ),
    path(
        "admin-portal/enrollment/adjustments/<int:log_id>/",
        enrollment_adjustment_detail_view,
        name="enrollment_adjustment_detail",
    ),
    path("admin-portal/enrollment/create/", enrollment_create_view, name="enrollment_create"),
    path(
        "admin-portal/enrollment/<int:enrollment_id>/edit/",
        enrollment_update_view,
        name="enrollment_update",
    ),
    path("admin-portal/grading/templates/", grading_template_list_view, name="grading_template_list"),
    path("admin-portal/grading/templates/create/", grading_template_create_view, name="grading_template_create"),
    path(
        "admin-portal/grading/templates/calculator/",
        grading_template_calculator_view,
        name="grading_template_calculator",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/structure/",
        grading_template_structure_view,
        name="grading_template_structure",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/builder/",
        grading_template_builder_view,
        name="grading_template_builder",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/edit/",
        grading_template_update_view,
        name="grading_template_update",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/duplicate/",
        grading_template_duplicate_view,
        name="grading_template_duplicate",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/publish/",
        grading_template_publish_view,
        name="grading_template_publish",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/submit-approval/",
        grading_template_submit_for_approval_view,
        name="grading_template_submit_for_approval",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/review-approval/",
        grading_template_review_approval_view,
        name="grading_template_review_approval",
    ),
    path(
        "admin-portal/grading/template-hotfixes/",
        template_hotfix_list_view,
        name="template_hotfix_list",
    ),
    path(
        "admin-portal/grading/templates/<int:template_id>/hotfix/create/",
        template_hotfix_create_view,
        name="template_hotfix_create",
    ),
    path(
        "admin-portal/grading/template-hotfixes/<int:hotfix_id>/review/",
        template_hotfix_review_view,
        name="template_hotfix_review",
    ),
    path("admin-portal/grading/periods/", template_period_list_view, name="template_period_list"),
    path("admin-portal/grading/periods/create/", template_period_create_view, name="template_period_create"),
    path(
        "admin-portal/grading/periods/<int:period_id>/edit/",
        template_period_update_view,
        name="template_period_update",
    ),
    path("admin-portal/grading/components/", template_component_list_view, name="template_component_list"),
    path(
        "admin-portal/grading/components/create/",
        template_component_create_view,
        name="template_component_create",
    ),
    path(
        "admin-portal/grading/components/<int:component_id>/edit/",
        template_component_update_view,
        name="template_component_update",
    ),
    path(
        "admin-portal/grading/components/<int:component_id>/delete/",
        template_component_delete_view,
        name="template_component_delete",
    ),
    path(
        "admin-portal/grading/subcomponents/",
        template_subcomponent_list_view,
        name="template_subcomponent_list",
    ),
    path(
        "admin-portal/grading/subcomponents/create/",
        template_subcomponent_create_view,
        name="template_subcomponent_create",
    ),
    path(
        "admin-portal/grading/subcomponents/<int:subcomponent_id>/edit/",
        template_subcomponent_update_view,
        name="template_subcomponent_update",
    ),
    path("admin-portal/grading/details/", template_detail_list_view, name="template_detail_list"),
    path("admin-portal/grading/details/create/", template_detail_create_view, name="template_detail_create"),
    path(
        "admin-portal/grading/details/<int:detail_id>/edit/",
        template_detail_update_view,
        name="template_detail_update",
    ),
    path(
        "admin-portal/grading/tenant-profiles/",
        tenant_grading_profile_list_view,
        name="tenant_grading_profile_list",
    ),
    path(
        "admin-portal/grading/tenant-profiles/create/",
        tenant_grading_profile_create_view,
        name="tenant_grading_profile_create",
    ),
    path(
        "admin-portal/grading/tenant-profiles/<int:profile_id>/edit/",
        tenant_grading_profile_update_view,
        name="tenant_grading_profile_update",
    ),
    path(
        "admin-portal/grading/tenant-profiles/<int:profile_id>/duplicate/",
        tenant_grading_profile_duplicate_view,
        name="tenant_grading_profile_duplicate",
    ),
    path(
        "admin-portal/grading/course-template-assignments/",
        course_template_assignment_list_view,
        name="course_template_assignment_list",
    ),
    path(
        "admin-portal/grading/course-template-assignments/create/",
        course_template_assignment_create_view,
        name="course_template_assignment_create",
    ),
    path(
        "admin-portal/grading/course-template-assignments/<int:assignment_id>/edit/",
        course_template_assignment_update_view,
        name="course_template_assignment_update",
    ),
    path(
        "admin-portal/grading/base-overrides/",
        course_base_override_list_view,
        name="course_base_override_list",
    ),
    path(
        "admin-portal/grading/base-overrides/create/",
        course_base_override_create_view,
        name="course_base_override_create",
    ),
    path(
        "admin-portal/grading/base-overrides/<int:override_id>/edit/",
        course_base_override_update_view,
        name="course_base_override_update",
    ),
    path("admin-portal/grading/period-locks/", grading_period_lock_list_view, name="grading_period_lock_list"),
    path(
        "admin-portal/grading/period-locks/create/",
        grading_period_lock_create_view,
        name="grading_period_lock_create",
    ),
    path(
        "admin-portal/grading/period-locks/<int:lock_id>/edit/",
        grading_period_lock_update_view,
        name="grading_period_lock_update",
    ),
    path(
        "admin-portal/grading/period-locks/<int:lock_id>/close/",
        grading_period_lock_close_view,
        name="grading_period_lock_close",
    ),
    path(
        "admin-portal/grading/period-locks/<int:lock_id>/reopen/",
        grading_period_lock_reopen_view,
        name="grading_period_lock_reopen",
    ),
    path(
        "admin-portal/grading/encoding-controls/",
        grade_encoding_control_list_view,
        name="grade_encoding_control_list",
    ),
    path(
        "admin-portal/grading/encoding-controls/create/",
        grade_encoding_control_create_view,
        name="grade_encoding_control_create",
    ),
    path(
        "admin-portal/grading/encoding-controls/<int:control_id>/edit/",
        grade_encoding_control_update_view,
        name="grade_encoding_control_update",
    ),
    path(
        "admin-portal/grading/encoding-controls/<int:control_id>/open/",
        grade_encoding_control_open_view,
        name="grade_encoding_control_open",
    ),
    path(
        "admin-portal/grading/encoding-controls/<int:control_id>/close/",
        grade_encoding_control_close_view,
        name="grade_encoding_control_close",
    ),
    path(
        "admin-portal/grading/submissions/",
        grade_submission_list_view,
        name="grade_submission_list",
    ),
    path(
        "admin-portal/grading/submissions/overdue-unsubmitted/",
        overdue_unsubmitted_report_view,
        name="overdue_unsubmitted_report",
    ),
    path(
        "admin-portal/grading/submissions/<int:submission_id>/reopen/",
        grade_submission_reopen_view,
        name="grade_submission_reopen",
    ),
    path(
        "admin-portal/grading/submission-reopen-requests/",
        grade_submission_reopen_request_list_view,
        name="grade_submission_reopen_request_list",
    ),
    path(
        "admin-portal/grading/submission-reopen-requests/<int:request_id>/review/",
        grade_submission_reopen_request_review_view,
        name="grade_submission_reopen_request_review",
    ),
    path(
        "admin-portal/grading/corrections/",
        grade_correction_request_list_view,
        name="grade_correction_request_list",
    ),
    path(
        "admin-portal/grading/corrections/create-on-behalf/",
        grade_correction_request_create_on_behalf_view,
        name="grade_correction_request_create_on_behalf",
    ),
    path(
        "admin-portal/grading/corrections/<int:request_id>/review/",
        grade_correction_request_review_view,
        name="grade_correction_request_review",
    ),
    path(
        "admin-portal/grading/corrections/<int:request_id>/official-report/",
        grade_correction_request_official_report_view,
        name="grade_correction_request_official_report",
    ),
    path(
        "admin-portal/grading/corrections/<int:request_id>/attachments/<int:attachment_id>/download/",
        grade_correction_attachment_download_view,
        name="grade_correction_attachment_download",
    ),
    path("admin-portal/imports/batches/", import_batch_list_view, name="import_batch_list"),
    path(
        "admin-portal/tools/academic-scope/",
        active_academic_term_settings_view,
        name="active_academic_term_settings",
    ),
    path(
        "admin-portal/tools/active-grading-period/",
        active_grading_period_settings_view,
        name="active_grading_period_settings",
    ),
    path(
        "admin-portal/tools/correction-governance/",
        correction_governance_settings_view,
        name="correction_governance_settings",
    ),
    path(
        "admin-portal/tools/document-print-settings/",
        document_print_settings_view,
        name="document_print_settings",
    ),
    path(
        "admin-portal/tools/configurable-features/",
        configurable_features_settings_view,
        name="configurable_features_settings",
    ),
    path(
        "admin-portal/tools/actual-data-reset/",
        actual_data_reset_view,
        name="actual_data_reset",
    ),
    path("admin-portal/tools/email-diagnostics/", email_diagnostics_view, name="email_diagnostics"),
    path("admin-portal/imports/batches/<int:batch_id>/", import_batch_detail_view, name="import_batch_detail"),
    path(
        "admin-portal/imports/batches/<int:batch_id>/errors.csv",
        import_batch_error_report_view,
        name="import_batch_error_report",
    ),
    path(
        "admin-portal/imports/batches/<int:batch_id>/confirm/",
        import_batch_confirm_view,
        name="import_batch_confirm",
    ),
    path(
        "admin-portal/imports/<slug:import_slug>/template/",
        import_template_download_view,
        name="import_template_download",
    ),
    path(
        "admin-portal/imports/<slug:import_slug>/upload/",
        import_upload_view,
        name="import_upload",
    ),
    path(
        "admin-portal/security/faculty-invitations/<int:invitation_id>/resend/",
        faculty_invitation_resend_view,
        name="faculty_invitation_resend",
    ),
]
