# Generated by Django 5.2.12 on 2026-08-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0010_stage6c_approve_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexamconfiguration',
            name='automatic_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseexamconfiguration',
            name='automatic_processing_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='courseexamconfiguration',
            name='automatic_processing_status',
            field=models.CharField(blank=True, choices=[('BLOCKED', 'Blocked'), ('GENERATED', 'Generated'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='courseexamconfiguration',
            name='reopened_contribution_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examgenerationrevision',
            name='generation_trigger',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=12),
        ),
        migrations.AddField(
            model_name='examinationcycle',
            name='processing_mode',
            field=models.CharField(choices=[('MANUAL_REVIEW', 'Manual Review'), ('AUTOMATIC_GENERATION', 'Automatic Generation')], default='MANUAL_REVIEW', max_length=24),
        ),
        migrations.AlterField(
            model_name='examgenerationrevision',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_departmental_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseexamconfiguration',
            index=models.Index(fields=['workflow_status', 'reopened_contribution_deadline'], name='idx_de_cfg_reopen_deadline'),
        ),
        migrations.AddConstraint(
            model_name='examgenerationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generated_by__isnull', True), ('generation_trigger', 'AUTOMATIC')), models.Q(('generated_by__isnull', False), ('generation_trigger', 'MANUAL')), _connector='OR'), name='ck_de_gen_trigger_actor'),
        ),
    ]
