# Generated by Django 5.2.12 on 2026-08-15 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0014_automatic_generation_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePrintRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print_from', models.DateTimeField()),
                ('print_until', models.DateTimeField()),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=8)),
                ('active_marker', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_print_releases', to='departmental_exams.cyclecourse')),
                ('generation_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_print_releases', to='departmental_exams.examgenerationrevision')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='released_departmental_exam_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_departmental_exam_questionnaire_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departmental_exam_questionnaire_print_releases',
                'indexes': [models.Index(fields=['cycle_course', 'status', 'print_from', 'print_until'], name='idx_de_print_release_window'), models.Index(fields=['generation_revision', 'status'], name='idx_de_print_release_revision')],
                'constraints': [models.UniqueConstraint(fields=('cycle_course', 'active_marker'), name='uq_de_print_release_active'), models.CheckConstraint(condition=models.Q(('print_until__gt', models.F('print_from'))), name='ck_de_print_release_window'), models.CheckConstraint(condition=models.Q(models.Q(('active_marker', 1), ('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('active_marker__isnull', True), ('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='ck_de_print_release_status')],
            },
        ),
    ]
