# Generated by Django 5.2.12 on 2026-08-25 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0020_personalized_answer_sheet_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCourseEquivalencyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_course_equivalency_groups', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_equivalency_groups', to='departmental_exams.examinationcycle')),
                ('primary_cycle_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_equivalency_groups', to='departmental_exams.cyclecourse')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_exam_course_equivalency_groups', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_exam_course_equivalency_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departmental_exam_course_equivalency_groups',
            },
        ),
        migrations.CreateModel(
            name='ExamCourseEquivalencyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_marker', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_exam_course_equivalency_memberships', to=settings.AUTH_USER_MODEL)),
                ('cycle_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalency_memberships', to='departmental_exams.cyclecourse')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='departmental_exams.examcourseequivalencygroup')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_exam_course_equivalency_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departmental_exam_course_equivalency_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='examcourseequivalencygroup',
            index=models.Index(fields=['cycle', 'is_active'], name='idx_de_equiv_group_active'),
        ),
        migrations.AddConstraint(
            model_name='examcourseequivalencygroup',
            constraint=models.UniqueConstraint(fields=('cycle', 'name'), name='uq_de_equiv_group_cycle_name'),
        ),
        migrations.AddConstraint(
            model_name='examcourseequivalencygroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('retired_at__isnull', True), ('retired_by__isnull', True), ('retirement_reason', '')), models.Q(('is_active', False), ('retired_at__isnull', False), ('retired_by__isnull', False), models.Q(('retirement_reason', ''), _negated=True)), _connector='OR'), name='ck_de_equiv_group_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='examcourseequivalencymembership',
            index=models.Index(fields=['group', 'active_marker', 'cycle_course'], name='idx_de_equiv_member_group'),
        ),
        migrations.AddConstraint(
            model_name='examcourseequivalencymembership',
            constraint=models.UniqueConstraint(fields=('group', 'cycle_course'), name='uq_de_equiv_member_group_course'),
        ),
        migrations.AddConstraint(
            model_name='examcourseequivalencymembership',
            constraint=models.UniqueConstraint(fields=('cycle_course', 'active_marker'), name='uq_de_equiv_member_active_course'),
        ),
        migrations.AddConstraint(
            model_name='examcourseequivalencymembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_marker', 1), ('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('active_marker__isnull', True), ('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='ck_de_equiv_member_lifecycle'),
        ),
    ]
