# Generated by Django 5.2.12 on 2026-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0021_examcourseequivalencygroup_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='ck_de_question_codes',
        ),
        migrations.AddField(
            model_name='questionimportbatch',
            name='source_format',
            field=models.CharField(choices=[('CSV', 'CSV'), ('DOCX', 'Word (.docx)')], default='CSV', max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='entry_method',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CSV', 'CSV'), ('DOCX', 'Word (.docx)')], default='MANUAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='questionimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source_format__in', ['CSV', 'DOCX'])), name='ck_de_batch_source_format'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answer__in', ['A', 'B', 'C', 'D']), ('difficulty__in', ['EASY', 'MODERATE', 'DIFFICULT']), ('entry_method__in', ['MANUAL', 'CSV', 'DOCX']), ('revision__gte', 1)), name='ck_de_question_codes'),
        ),
    ]
