# Generated by Django 5.2.12 on 2026-09-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0023_faculty_source_eligibility_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examblueprint',
            name='structure_final_item_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='structure_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='structure_frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frozen_exam_blueprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='examblueprint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('structure_final_item_count__isnull', True), ('structure_frozen_at__isnull', True), ('structure_frozen_by__isnull', True)), models.Q(('structure_final_item_count__gte', 1), ('structure_frozen_at__isnull', False), ('structure_frozen_by__isnull', False)), _connector='OR'), name='ck_de_blueprint_freeze_evidence'),
        ),
    ]
