# Generated by Django 5.2.12 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departmental_exams", "0024_structured_exam_lifecycle_freeze"),
    ]

    operations = [
        migrations.AddField(
            model_name="examscenario",
            name="content_format",
            field=models.CharField(
                choices=[
                    ("PLAIN_TEXT", "Plain text"),
                    ("RICH_HTML_V1", "Rich HTML V1"),
                ],
                default="PLAIN_TEXT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="examscenario",
            name="contribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculty_scenarios",
                to="departmental_exams.facultycontribution",
            ),
        ),
        migrations.AlterField(
            model_name="examscenario",
            name="stimulus",
            field=models.TextField(max_length=50000),
        ),
        migrations.AddIndex(
            model_name="examscenario",
            index=models.Index(
                fields=["contribution", "created_at"],
                name="idx_de_scenario_contrib",
            ),
        ),
    ]
