# Generated by Django 5.2.12 on 2026-09-11 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def classify_legacy(apps, schema_editor):
    apps.get_model("departmental_exams", "AnswerKeyRelease").objects.using(
        schema_editor.connection.alias
    ).all().update(scope_kind="LEGACY_UNSCOPED")


def prevent_scope_loss(apps, schema_editor):
    if apps.get_model("departmental_exams", "AnswerKeyRelease").objects.using(
        schema_editor.connection.alias
    ).filter(scope_kind="SCOPED").exists():
        raise IrreversibleError(
            "Scoped Answer Key history exists. Reversal would remove recipient boundaries; "
            "use a separately reviewed recovery plan. No automatic merge is permitted."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0024_structured_exam_lifecycle_freeze'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerkeyrelease',
            name='uq_de_key_release_active',
        ),
        migrations.AddField(
            model_name='answerkeyrelease',
            name='recipient_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_answer_key_releases', to='departmental_exams.cyclecourse'),
        ),
        migrations.AddField(
            model_name='answerkeyrelease',
            name='scope_kind',
            field=models.CharField(choices=[('SCOPED', 'Campus/course scoped'), ('LEGACY_UNSCOPED', 'Legacy unscoped - reissue required')], default='SCOPED', max_length=16),
        ),
        migrations.AddField(
            model_name='answerkeyrelease',
            name='target_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_key_releases', to='tenants.campus'),
        ),
        migrations.RunPython(classify_legacy, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='answerkeyrelease',
            constraint=models.UniqueConstraint(fields=('recipient_course', 'target_campus', 'active_marker'), name='uq_de_key_target_active'),
        ),
        migrations.AddConstraint(
            model_name='answerkeyrelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient_course__isnull', False), ('scope_kind', 'SCOPED'), ('target_campus__isnull', False)), models.Q(('recipient_course__isnull', True), ('scope_kind', 'LEGACY_UNSCOPED'), ('target_campus__isnull', True)), _connector='OR'), name='ck_de_key_target_scope'),
        ),
        migrations.RunPython(migrations.RunPython.noop, prevent_scope_loss),
    ]
