# Generated by Django 5.2.12 on 2026-09-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0029_question_import_target_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimportbatch',
            name='duplicate_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='QuestionIdentityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('bundle_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('import_row_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departmental_exams.questionimportbatch')),
                ('primary_cycle_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmental_exams.cyclecourse')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departmental_exams.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('primary_cycle_course', 'version', 'fingerprint'), name='uq_de_logical_reservation'),
                    models.CheckConstraint(condition=(models.Q(question__isnull=False, import_batch__isnull=True, import_row_number__isnull=True) | models.Q(question__isnull=True, import_batch__isnull=False, import_row_number__isnull=False)), name='ck_de_logical_owner')],
            },
        ),
    ]
