# Generated by Django 5.2.12 on 2026-09-16 12:51

from django.db import migrations, models
from django.db.models.functions import Length


def preserve_rich_question_history(apps, schema_editor):
    """Refuse a schema rollback once it would discard immutable v4 evidence."""
    alias = schema_editor.connection.alias
    Question = apps.get_model("departmental_exams", "Question")
    Item = apps.get_model("departmental_exams", "GeneratedExamItem")
    Source = apps.get_model("departmental_exams", "GenerationSourceQuestionSnapshot")
    Set = apps.get_model("departmental_exams", "GeneratedExamSet")
    Reservation = apps.get_model("departmental_exams", "QuestionIdentityReservation")
    Batch = apps.get_model("departmental_exams", "QuestionImportBatch")
    if (
        Question.objects.using(alias).exclude(content_format="PLAIN_TEXT").exists()
        or Item.objects.using(alias).exclude(question_content_format_snapshot="PLAIN_TEXT").exists()
        or Source.objects.using(alias).exclude(question_content_format_snapshot="PLAIN_TEXT").exists()
        or Set.objects.using(alias).exclude(structured_content_digest_version="").exists()
        or Reservation.objects.using(alias).filter(version="course-question-v4").exists()
        or Question.objects.using(alias).annotate(_rich_question_length=Length("question_text")).filter(_rich_question_length__gt=5000).exists()
        or any(
            len(getattr(question, field) or "") > 1000
            for question in Question.objects.using(alias).only("choice_a", "choice_b", "choice_c", "choice_d").iterator()
            for field in ("choice_a", "choice_b", "choice_c", "choice_d")
        )
        or any(
            isinstance(batch.duplicate_plan, dict)
            and any(
                isinstance(decision, dict)
                and decision.get("identity_version") == "course-question-v4"
                for decision in batch.duplicate_plan.values()
            )
            for batch in Batch.objects.using(alias).only("duplicate_plan").iterator()
        )
    ):
        raise RuntimeError(
            "Rich MCQ content or v4 immutable identity evidence exists; this migration cannot be reversed safely."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0030_course_question_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexamitem',
            name='question_content_format_snapshot',
            field=models.CharField(choices=[('PLAIN_TEXT', 'Plain text'), ('RICH_HTML_V1', 'Rich HTML V1')], default='PLAIN_TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedexamset',
            name='structured_content_digest_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='generationsourcequestionsnapshot',
            name='question_content_format_snapshot',
            field=models.CharField(choices=[('PLAIN_TEXT', 'Plain text'), ('RICH_HTML_V1', 'Rich HTML V1')], default='PLAIN_TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='content_format',
            field=models.CharField(choices=[('PLAIN_TEXT', 'Plain text'), ('RICH_HTML_V1', 'Rich HTML V1')], default='PLAIN_TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedexamitem',
            name='question_text_snapshot',
            field=models.TextField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='generationsourcequestionsnapshot',
            name='question_text_snapshot',
            field=models.TextField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.TextField(max_length=12000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.TextField(max_length=12000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.TextField(max_length=12000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.TextField(max_length=12000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=25000),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_rich_question_history),
    ]
