# Generated by Django 5.2.12 on 2026-09-28 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_exam_department'),
        ('departmental_exams', '0034_question_bank_owner_revisions'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEquivalencyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_equivalency_definitions', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_exam_equivalency_definitions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_equivalency_definitions', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_exam_equivalency_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departmental_exam_equivalency_definitions',
            },
        ),
        migrations.CreateModel(
            name='CourseEquivalencyDefinitionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_equivalency_revisions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='departmental_exams.courseequivalencydefinition')),
                ('primary_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exam_equivalency_revisions', to='academics.course')),
            ],
            options={
                'db_table': 'departmental_exam_equivalency_revisions',
            },
        ),
        migrations.CreateModel(
            name='CourseEquivalencyDefinitionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(max_length=50)),
                ('title_snapshot', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_equivalency_definition_memberships', to='academics.course')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='departmental_exams.courseequivalencydefinitionrevision')),
            ],
            options={
                'db_table': 'departmental_exam_equivalency_revision_members',
            },
        ),
        migrations.CreateModel(
            name='CourseEquivalencyCyclePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BLOCKED', 'Needs correction'), ('APPLIED', 'Applied'), ('NOT_APPLICABLE', 'Fewer than two members present'), ('EXCEPTED', 'Cycle exception')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('exception_at', models.DateTimeField(blank=True, null=True)),
                ('exception_reason', models.CharField(blank=True, max_length=500)),
                ('applied_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definition_plans', to='departmental_exams.examcourseequivalencygroup')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalency_plans', to='departmental_exams.examinationcycle')),
                ('exception_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_equivalency_cycle_exceptions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_plans', to='departmental_exams.courseequivalencydefinition')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_plans', to='departmental_exams.courseequivalencydefinitionrevision')),
            ],
            options={
                'db_table': 'departmental_exam_equivalency_cycle_plans',
            },
        ),
        migrations.CreateModel(
            name='ExamBlueprintDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('evidence', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_blueprint_dispositions', to=settings.AUTH_USER_MODEL)),
                ('blueprint', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historical_disposition', to='departmental_exams.examblueprint')),
                ('primary_blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retained_secondary_blueprints', to='departmental_exams.examblueprint')),
            ],
            options={
                'db_table': 'departmental_exam_blueprint_dispositions',
            },
        ),
        migrations.AddIndex(
            model_name='courseequivalencydefinition',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_de_eqdef_active'),
        ),
        migrations.AddConstraint(
            model_name='courseequivalencydefinitionrevision',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='uq_de_eqdef_revision'),
        ),
        migrations.AddConstraint(
            model_name='courseequivalencydefinitionmember',
            constraint=models.UniqueConstraint(fields=('revision', 'course'), name='uq_de_eqrev_member'),
        ),
        migrations.AddIndex(
            model_name='courseequivalencycycleplan',
            index=models.Index(fields=['cycle', 'status'], name='idx_de_eqplan_status'),
        ),
        migrations.AddConstraint(
            model_name='courseequivalencycycleplan',
            constraint=models.UniqueConstraint(fields=('cycle', 'definition'), name='uq_de_eqplan_cycle_def'),
        ),
    ]
