# Generated by Django 5.2.12 on 2026-09-29 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmental_exams', '0035_persistent_course_equivalency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBlueprintRestoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('evidence', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_blueprint_restorations', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='restoration', to='departmental_exams.examblueprintdisposition')),
                ('retired_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_restorations', to='departmental_exams.examcourseequivalencygroup')),
            ],
            options={
                'db_table': 'departmental_exam_blueprint_restorations',
            },
        ),
    ]
