# Generated by Django 5.2.12 on 2026-03-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("courses", "Courses"),
                            ("course_offerings", "Course Offerings"),
                            ("faculty_assignments", "Faculty Assignments"),
                            ("enrollment", "Enrollment"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALIDATED", "Validated"),
                            ("VALIDATION_FAILED", "Validation Failed"),
                            ("CONFIRMED", "Confirmed"),
                            ("CONFIRM_FAILED", "Confirm Failed"),
                        ],
                        default="VALIDATED",
                        max_length=24,
                    ),
                ),
                ("source_file", models.FileField(blank=True, null=True, upload_to="imports/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255, null=True)),
                ("expected_headers_json", models.JSONField(default=list)),
                ("actual_headers_json", models.JSONField(default=list)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("error_summary_json", models.JSONField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, null=True)),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="tenants.campus",
                    ),
                ),
                (
                    "confirmed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches_confirmed",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches_uploaded",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "import_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatchRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                (
                    "row_status",
                    models.CharField(
                        choices=[("VALID", "Valid"), ("ERROR", "Error"), ("IMPORTED", "Imported")],
                        default="VALID",
                        max_length=16,
                    ),
                ),
                ("raw_data_json", models.JSONField(default=dict)),
                ("normalized_data_json", models.JSONField(blank=True, null=True)),
                ("errors_json", models.JSONField(blank=True, null=True)),
                ("imported_entity_type", models.CharField(blank=True, max_length=120, null=True)),
                ("imported_entity_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "import_batch_rows",
                "ordering": ["row_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"), name="uq_import_batch_rows_batch_row"
                    )
                ],
            },
        ),
    ]
