# Generated by Django 5.2.12 on 2026-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('sections', 'Sections'), ('courses', 'Courses'), ('course_offerings', 'Course Offerings'), ('faculty_assignments', 'Faculty Assignments'), ('enrollment', 'Enrollment')], max_length=40),
        ),
    ]
