# Generated by Django 5.2.12 on 2026-03-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_importbatch_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatchrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='imports.importbatch'),
        ),
    ]
