# Generated by Django 5.2.12 on 2026-04-25 09:32

import apps.core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_importbatchrow_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.upload_paths.import_source_upload_path),
        ),
    ]
