# Generated by Django 5.2.12 on 2026-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_importbatch_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('sections', 'Sections'), ('courses', 'Courses'), ('students', 'Students'), ('course_offerings', 'Course Offerings'), ('faculty_assignments', 'Faculty Assignments'), ('enrollment', 'Enrollment')], max_length=40),
        ),
    ]
