# Generated by Django 5.2.12 on 2026-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_add_student_import_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='email_system_enabled_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='send_invitation_emails_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importbatchrow',
            name='result_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='importbatchrow',
            name='result_metadata_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('sections', 'Sections'), ('courses', 'Courses'), ('students', 'Students'), ('course_offerings', 'Course Offerings'), ('faculty_assignments', 'Faculty Assignments'), ('faculty_users', 'Faculty Users'), ('enrollment', 'Enrollment')], max_length=40),
        ),
    ]
