from __future__ import annotations


FACULTY_HELP_SECTIONS = [
    {
        "code": "departmental-exam-contributions",
        "title": "Departmental Exam Question Contributions",
        "topics": [
            {
                "code": "question-contribution-workspace",
                "title": "Prepare and Submit Your Question Contribution",
                "purpose": "Lets an eligible assigned faculty member prepare the exact course quota of private plain-text multiple-choice questions.",
                "how_to_open": ["From the Faculty Portal navigation, open Departmental Exam Builder.", "Choose Question Contributions, then open the grouped course workspace."],
                "check_first": ["Confirm the cycle, grouped course, campuses, coverage, quota, instructions, and deadline.", "A blocked Draft remains readable but cannot be changed.", "A Submitted contribution is final and read-only."],
                "actions": [
                    {"name": "Add or Edit Question", "does": "Saves plain-text question text, four distinct choices, one correct answer, and Easy, Moderate, or Difficult difficulty.", "when": "Use it while the contribution is an Active Draft and before the deadline.", "avoid": "Do not enter HTML, images, another contributor's content, or more than the exact quota.", "result": "The question is saved in your private workspace with a stable position.", "editable": "Editable only while the contribution remains an Active Draft."},
                    {"name": "Reorder or Delete", "does": "Changes your complete owned question order or removes one Draft question and closes the position gap.", "when": "Use it before final submission.", "avoid": "Do not omit questions from a reorder request.", "result": "Positions remain one-based and stable.", "editable": "Not available when blocked or submitted."},
                    {"name": "Download and Upload CSV", "does": "Downloads the exact UTF-8 template, validates an append-only CSV, and creates a confidential server-side preview for 30 minutes.", "when": "Use it for multiple questions after replacing or deleting the labeled sample row.", "avoid": "Do not change header spelling, order, case, or spacing; do not exceed 2 MB, 200 nonblank rows, or the remaining quota.", "result": "Errors and warning-only duplicates appear by row; confirmation imports all rows or none.", "editable": "Imported questions remain editable Draft questions until final submission."},
                    {"name": "Final Submission", "does": "Rechecks current assignment eligibility, lifecycle, deadline, exact quota, revisions, and every question before making the contribution read-only.", "when": "Use it only when the saved count exactly equals the quota and every question is final.", "avoid": "Do not expect a Return, Reopen, or grace-period override in Stage 5.", "result": "The contribution becomes Submitted once; repeated confirmation does not duplicate submission.", "editable": "No. Submitted content remains owner-readable and immutable."},
                    {"name": "Print Questionnaire", "does": "Shows separate Print Set A and Print Set B actions only for the exact generated revision released by an administrator, with Letter as the default paper size and A4 or Legal as options.", "when": "Use a print action only while the current time is inside its Print From/Print Until window and your accepted teaching assignment remains valid; choose the paper size before opening the browser print dialog.", "avoid": "Do not expect a regenerated revision to appear until it receives a new release, and do not share the confidential questionnaire. Faculty do not receive Answer Keys, Question Selection Audit reports, or Automatic Generation Audit reports.", "result": "The released exact revision opens as sanitized printer-friendly HTML with the official tenant header, course scope, questions, choices, and print timestamp, without answers or internal generation metadata.", "editable": "No. Printing is read-only, audited, and denied outside the exact release window."},
                ],
                "avoid": "Never share another contributor's questions, preview link, correct answers, or confidential CSV content.",
                "next_step": "If contribution or print access is blocked or missing, contact the authorized academic office to verify your current assignment and the exact questionnaire release window.",
            }
        ],
    },
    {
        "code": "start",
        "title": "Start and Check Your Classes",
        "topics": [
            {
                "code": "login",
                "title": "Sign In and Confirm Your Account",
                "purpose": "Opens the Faculty Portal using your own TeacherMate+ account.",
                "check_first": ["Use your assigned username.", "Confirm the page says Faculty Portal.", "Use Forgot Password only for your own account."],
                "actions": [
                    {"name": "Start with Login", "does": "Signs you in and opens your faculty work area.", "when": "Use it after entering your correct credentials.", "avoid": "Do not use another faculty member's account.", "result": "Your dashboard and permitted classes are displayed. If a password change is required, navigation stays collapsed and locked until the new password is saved successfully.", "editable": "No grades change."},
                    {"name": "Forgot Password", "does": "Sends a reset link to an eligible faculty account.", "when": "Use it when you cannot remember your password.", "avoid": "Do not repeatedly request links; use the newest email.", "result": "A reset notification is sent when the account is valid.", "editable": "Only the password changes after successful reset."},
                ],
                "avoid": "Never share your password, OTP, or reset link.",
                "next_step": "Open My Classes and check your assigned teaching load.",
            },
            {
                "code": "assignments",
                "title": "Assigned Classes",
                "purpose": "Shows the classes officially assigned to you for the selected academic scope.",
                "how_to_open": ["From the left navigation bar, click My Classes."],
                "screenshot": "faculty_helpguide/1_myclasses.png",
                "check_first": ["Check the campus, academic year, and term.", "Check the course, section, schedule, room, and grading template.", "Report a wrong class before accepting it."],
                "actions": [
                    {"name": "Accept", "does": "Confirms that the teaching assignment is correct.", "when": "Use it after checking all class details.", "avoid": "Do not accept a class that is not yours.", "result": "The class moves to Accepted Course Assignments and grading actions become available.", "editable": "Faculty cannot undo acceptance from the Faculty Portal. If the load is wrong after acceptance, contact the assigning admin or academic office so they can unassign or replace it."},
                    {"name": "Request Clarification", "does": "Returns the assignment to admin with your concern.", "when": "Use it for a wrong course, section, schedule, or load detail.", "avoid": "Do not accept first when the assignment is clearly incorrect.", "result": "Admin can review your message and correct the assignment.", "editable": "You may respond again after admin resolves it."},
                    {"name": "Decline", "does": "Records that you cannot accept the assignment.", "when": "Use it only for an official load issue.", "avoid": "Do not decline merely because setup is incomplete; request clarification instead.", "result": "The assignment remains visible for administrative follow-up.", "editable": "Admin governs any later reassignment."},
                ],
                "avoid": "Do not encode scores until the class list and grading template are correct.",
                "next_step": "Open Grading, choose a period, and review the required activity categories.",
            },
            {
                "code": "exit-pulse",
                "title": "Exit Pulse Learning Check",
                "purpose": "Runs confidential, identity-validated classroom feedback for instructional reflection. Student identity is securely retained for accountability but hidden from routine faculty results. Exit Pulse is not grading, attendance, faculty evaluation, or ranking.",
                "how_to_open": ["From the left navigation bar, open Classroom Tools.", "Click Exit Pulse to open the dashboard, or use Exit Pulse Guide on that page to return to this guide section.", "Use Create Exit Pulse for a new Learning Check, View History for one class, or Assignment Comparison for your own authorized assignments."],
                "check_first": [
                    "Choose the correct accepted class and enter the lesson topic.",
                    "Choose one of the three learning questions, or write a custom question about understanding, confidence, clarification, examples, or practice.",
                    "Enable optional written feedback only when you want one or both short prompts.",
                ],
                "actions": [
                    {"name": "Create a Session", "does": "Selects your accepted assignment, lesson topic, predefined or safe custom learning question, and optional written-feedback prompts, then creates a secure QR link for five minutes.", "when": "Use one focused question near the end of a lesson after checking the class and prompt.", "avoid": "Do not request sensitive personal information or ask students to rate the faculty member.", "result": "The QR page opens enrollment verification before showing the learning-response form.", "editable": "You may extend once by five minutes, close early, or cancel."},
                    {"name": "Student Participation", "does": "Asks the student to scan the QR code, enter their student number, read the privacy notice, and submit one response after exact class-enrollment validation.", "when": "Students participate only while the session is live.", "avoid": "Do not collect student numbers separately or use Exit Pulse as an attendance list.", "result": "Entering and submitting the student number acknowledges the displayed privacy notice; there is no separate consent checkbox. One validated enrollment may submit once per session.", "editable": "Student identity is securely linked for accountability but hidden from routine faculty results."},
                    {"name": "View Results", "does": "Shows aggregate counts, percentages, response rate, understanding rate, support-needed rate, and enabled confidential comments without responder identity.", "when": "Use it after the session closes or expires.", "avoid": "Do not try to identify students or use responses as attendance, grades, or evidence of faculty performance.", "result": "A session summary identifies material that may need clarification or practice. Older sessions without a stored enrollment count label the current class count and response rate as estimates.", "editable": "Results are read-only and available only to the assigned faculty owner."},
                    {"name": "Review Dashboard", "does": "Shows your recent completed sessions and neutral weighted response, understanding, and support-needed summaries for the selected academic year and term.", "when": "Use it to review patterns across Learning Checks that you own.", "avoid": "Do not treat the summaries as student attendance, grades, or a faculty ranking.", "result": "Legacy sessions without a stored historical enrollment count are clearly marked and are excluded from the weighted response-rate denominator.", "editable": "The dashboard is read-only."},
                    {"name": "Open Class History", "does": "Lists completed Exit Pulse sessions for one current or historical assignment with date, question type, topic, and status filters and 20-row pagination.", "when": "Use View History from the dashboard when you need older session results.", "avoid": "Do not copy or disclose confidential written feedback; open the owner-only result only when needed.", "result": "Only your own tenant- and campus-scoped history is available. The original faculty owner retains read-only history after replacement; replacement faculty do not inherit it.", "editable": "Historical assignments cannot start new sessions."},
                    {"name": "Compare Assignments", "does": "Compares terminal-session counts, distinct topics, weighted response rate, understanding, support needed, and the latest completed survey across your authorized assignments.", "when": "Use Assignment Comparison when you want an aggregate instructional view across current classes or your own historical classes with completed Exit Pulse data.", "avoid": "Do not use the comparison for faculty ranking, evaluation, attendance, or grading. Written feedback is never included.", "result": "Filters and summary cards use the same academic-year, term, and question-type scope. Legacy sessions without a historical denominator are excluded only from weighted response-rate calculations.", "editable": "The comparison is read-only and limited to the authenticated faculty owner, tenant, and campus."},
                    {"name": "Privacy and Accountability", "does": "Keeps student numbers and names out of routine faculty pages while retaining a restricted enrollment link for legitimate institutional accountability.", "when": "Use aggregate results for normal instructional reflection. Report threats, abuse, discrimination, or serious misconduct through the authorized school process.", "avoid": "Faculty must not attempt to reveal or infer responder identity.", "result": "Any future identity investigation requires a separate permission, tenant/campus scope, a legitimate reason, and an audit record; no faculty reveal control exists.", "editable": "Institutional investigation access and retention require approved governance."},
                    {"name": "Troubleshoot Participation", "does": "Checks common issues such as an unverified student number, wrong section, expired session, prior submission, QR-link failure, missing historical denominator, or replacement-faculty history denial.", "when": "Ask the student to check the registered number and exact class first, then contact the appropriate academic office if the enrollment record is wrong.", "avoid": "Do not disclose whether a student number exists in another class, section, campus, or tenant.", "result": "Generic public errors protect enrollment privacy while authorized staff correct source records through established workflows.", "editable": "Faculty cannot override enrollment verification or historical ownership."},
                ],
                "avoid": "Use neutral prompts, review feedback constructively, and never use Exit Pulse for attendance, grading, faculty evaluation, ranking, or informal identity investigation.",
                "next_step": "Use aggregate patterns to decide whether to review the topic, give more examples, or provide more practice. Seek administrative assistance for enrollment errors or serious misconduct.",
            },
            {
                "code": "dashboard",
                "title": "Dashboard and Grade Encoding Status",
                "purpose": "Shows your accepted classes, current-period encoding status, and gradebook blockers without displaying student names. Detailed update, encoding-status, issue, analytics, performance-trend, and activity-history panels are intentionally hidden on phone-width screens.",
                "how_to_open": ["From the left navigation bar, click Dashboard."],
                "screenshot": "faculty_helpguide/1_dashboard.png",
                "check_first": ["Confirm the academic scope.", "Check each class period and status.", "Open Pending Grade Issues before a deadline."],
                "actions": [
                    {"name": "Open My Classes", "does": "Opens your accepted teaching assignments.", "when": "Use it to enter a class or grading period.", "avoid": "Do not use another faculty member's account to open a class.", "result": "Your assigned class cards are displayed.", "editable": "No records change."},
                    {"name": "Continue Encoding", "does": "Opens the selected period's activity workspace.", "when": "Use it for Not Started or In Progress gradebooks.", "avoid": "Do not encode until the class list and grading setup are correct.", "result": "You can continue creating activities or entering scores while policy permits.", "editable": "The gradebook remains editable only while open."},
                    {"name": "Review / Submit Grades", "does": "Opens the Summary when required records appear complete.", "when": "Use it after checking activities, scores, and attendance.", "avoid": "Do not submit without reviewing the Summary.", "result": "The current computed gradebook is displayed for review. On phones, the grade table shows wrapped student names, the current official periodic grade, and Explain.", "editable": "Submission locks normal editing."},
                    {"name": "View Performance", "does": "Opens the selected class snapshot and students requiring attention.", "when": "Use it after scores are encoded.", "avoid": "Do not present a partial snapshot as a final submitted grade.", "result": "Class average, risk count, missing outputs, weakest component, and attention rows are displayed.", "editable": "No grade records change."},
                ],
                "avoid": "The dashboard intentionally does not show student names or student-level alerts. Open a selected class to review those records privately.",
                "next_step": "Resolve Pending Grade Issues or open View Performance for one class.",
            },
            {
                "code": "feedback",
                "title": "Send Page Feedback",
                "purpose": "Lets you quickly tell the system team whether the current Faculty Portal page felt helpful, neutral, or difficult.",
                "how_to_open": ["Use Feedback in the bottom-left utility controls on an authenticated Faculty Portal page. On a phone, open Help & Privacy first."],
                "check_first": [
                    "Stay on the page you want to comment about.",
                    "Choose Happy, Neutral, or Sad.",
                    "Add a short suggestion only if it helps explain the rating.",
                ],
                "actions": [
                    {"name": "Submit Feedback", "does": "Sends your selected rating and optional suggestion without leaving the current page.", "when": "Use it when a page is confusing, helpful, or could be improved.", "avoid": "Do not include student names, grades, passwords, or other confidential information.", "result": "TeacherMate+ records the feedback for authorized admin review.", "editable": "Feedback is append-only from the Faculty Portal."},
                ],
                "avoid": "Do not use Feedback for urgent grade corrections, enrollment changes, or password problems. Use the official workflow for those requests.",
                "next_step": "Continue your class, activity, score, attendance, or summary work on the same page.",
            },
            {
                "code": "classlist",
                "title": "Class List and Student Status",
                "purpose": "Shows the official students included in your assigned class and the status used for grading readiness.",
                "how_to_open": ["Click My Classes.", "Find the accepted class.", "Click Class List."],
                "check_first": ["Confirm the course and section.", "Compare the list with the official enrollment record.", "Check non-active statuses such as DRP, WITHDRAWN, or INC carefully."],
                "actions": [
                    {"name": "Class List", "does": "Opens the current enrolled-student list.", "when": "Use it before encoding and whenever enrollment changes are reported.", "avoid": "Do not add or remove students outside the permitted roster workflow.", "result": "The active class roster and available status actions are displayed.", "editable": "Roster editing depends on the school's Class Master List Ownership setting."},
                    {"name": "Save Status", "does": "Records an allowed student enrollment status change.", "when": "Use it only with the required academic basis and within the allowed period.", "avoid": "Do not mark DRP, WITHDRAWN, or INC merely to bypass missing-score checks.", "result": "The student's grading readiness and report status are updated.", "editable": "Later changes remain subject to policy and audit."},
                ],
                "avoid": "Report a missing or extra student immediately; do not encode a different student under the wrong record.",
                "next_step": "Return to the period gradebook after the official roster is correct.",
            },
        ],
    },
    {
        "code": "encode",
        "title": "Create Activities and Record Results",
        "topics": [
            {
                "code": "activities",
                "title": "Activities",
                "purpose": "Creates the quizzes, recitations, assignments, activities, examinations, or other items students will complete.",
                "how_to_open": [
                    "Click the Grade Activities button from the periodic card.",
                    "Select a component.",
                    "Select a subcomponent.",
                    "Select a detail, when the template asks for one.",
                    "Type the activity title.",
                    "Enter the total items or highest possible score.",
                    "Choose the date conducted.",
                    "If the date is in the future, expect a TeacherMate+ reminder email for that activity when reminders are enabled.",
                ],
                "screenshot": "faculty_helpguide/2_activities.png",
                "check_first": ["Choose the correct grading period and category.", "Enter the correct highest possible score.", "Check the effective Score Entry rule shown by the form."],
                "actions": [
                    {"name": "Add Activity", "does": "Creates one graded item.", "when": "Use it when the item will be scored for the class.", "avoid": "Do not create duplicate activity names for the same task.", "result": "The item appears on the Activities, Score Entry, and Summary pages.", "editable": "It can be edited before submission while the gradebook is open."},
                    {"name": "Edit", "does": "Corrects the activity title, date, score, or category.", "when": "Use it before encoding is finalized.", "avoid": "Do not change the highest score after encoding without reviewing every student's result.", "result": "The summary recomputes from the updated activity information.", "editable": "Only while governance permits."},
                    {"name": "Delete", "does": "Removes an eligible activity.", "when": "Use it only when the item should not be part of grading.", "avoid": "Do not delete an activity to hide low or missing scores.", "result": "The item no longer contributes to the gradebook.", "editable": "A deleted item may need to be recreated if removed by mistake."},
                ],
                "avoid": "For Participation/Output, create only the details and activities that should count. Every created item, such as Recitation 1, Recitation 2, Assignment 1, Assignment 2, Seatwork 1, and Seatwork 2, counts equally in the average. Faculty do not assign a separate percentage weight to each detail.",
                "next_step": "Open Encode Scores for the activity.",
            },
            {
                "code": "scores",
                "title": "Encode Scores: Blank, Zero, and Base-50",
                "purpose": "Records each student's actual result for one activity.",
                "how_to_open": ["From the Activities page, click the activity's encoding icon button.", "Choose Start Encoding.", "Enter the scores.", "Click Save Scores."],
                "screenshot": "faculty_helpguide/2_encodescores.png",
                "check_first": ["Confirm the activity and highest possible score.", "Confirm the student list.", "Enter the actual raw score earned by each student."],
                "actions": [
                    {"name": "Save Scores", "does": "Saves the entered student scores.", "when": "Use it after reviewing every value on the page.", "avoid": "Do not leave the page with unsaved changes.", "result": "Saved scores are included in the summary computation.", "editable": "Yes, while the gradebook remains open."},
                    {"name": "Clear Score", "does": "Removes the student's score record.", "when": "Use it when a value was entered by mistake and the real score is not yet known.", "avoid": "Do not clear a score to mean zero.", "result": "The score becomes blank and may block submission.", "editable": "A valid score can be entered later."},
                ],
                "avoid": "A saved 0 is complete and counts in computation. A blank score is missing and can block submission. TeacherMate+ uses Raw Score Base-50, so raw 0 is transmuted to 50.",
                "next_step": "Save, then open Summary and check the computed averages.",
            },
            {
                "code": "attendance",
                "title": "Attendance",
                "purpose": "Records student attendance for a dated class session and supplies attendance grading when required.",
                "how_to_open": ["Click the Attendance button.", "Add a session date.", "Type the title or description.", "Click Save Session.", "Mark attendance for the listed students and save the records."],
                "screenshot": "faculty_helpguide/2_attendance.png",
                "check_first": ["Confirm the session date and class.", "Check that all active students are listed.", "Use the status that matches the official attendance record."],
                "actions": [
                    {"name": "Add Session", "does": "Creates a dated attendance meeting.", "when": "Use it for an actual class session.", "avoid": "Do not create duplicate sessions for the same meeting.", "result": "The session becomes available for attendance encoding.", "editable": "Yes, while the gradebook is open."},
                    {"name": "Save Attendance", "does": "Saves Present, Late, Absent, or Excused entries.", "when": "Use it after checking the entire class.", "avoid": "Do not leave a required status blank.", "result": "Attendance records and any required attendance score are updated.", "editable": "Yes, while the gradebook is open."},
                ],
                "avoid": "Absent is a recorded result, not a blank record. Current attendance scoring uses Present 100, Excused 100, Late 90, and Absent 0.",
                "next_step": "Open Summary and resolve any missing attendance records.",
            },
        ],
    },
    {
        "code": "understand",
        "title": "Understand and Check the Grade",
        "topics": [
            {
                "code": "summary",
                "title": "Summary of Periodic Grades",
                "purpose": "Shows activity scores, category averages, component totals, and the computed period grade.",
                "how_to_open": ["Click My Classes.", "Open the accepted class.", "Choose the grading period.", "Click Summary.", "Review Period Snapshot first, then review the grade table before submission."],
                "screenshot": "faculty_helpguide/3_summary.png",
                "check_first": ["Check the highest possible score row.", "Look for blanks, unexpected zeros, and wrong student statuses.", "Confirm all expected activities appear."],
                "actions": [
                    {"name": "Summary", "does": "Displays the current computed gradebook.", "when": "Use it after every major encoding session and before submission.", "avoid": "Do not submit based only on one activity page.", "result": "The latest saved records are shown using the assigned template.", "editable": "The summary itself is read-only; change source scores or activities."},
                    {"name": "Print Periodic Grades", "does": "Opens the submitted official periodic-grade HTML report in a new tab.", "when": "Use it after the period status is Submitted, then choose Print from the report preview.", "avoid": "Do not treat a Draft or Reopened working gradebook as an official report.", "result": "The full applicable roster, grouped Participation/Output and Quiz items, averages, and official grade columns are displayed for legal-landscape printing.", "editable": "No records change."},
                    {"name": "Grade Explanation", "does": "Shows how one student's grade was produced.", "when": "Use it when explaining a grade or checking an unexpected result.", "avoid": "Do not compare students or disclose another student's records.", "result": "The calculation path and source values are displayed.", "editable": "No records change."},
                    {"name": "Who Viewed", "does": "Shows recorded gradebook viewing activity.", "when": "Use it when checking access history.", "avoid": "Do not treat a view record as proof that a user changed a grade.", "result": "Available access records are displayed.", "editable": "No."},
                ],
                "avoid": "Q.AVE means Quiz Average, R.AVE means Recitation Average, P/O AVE means Participation/Output Average, and CS AVE means the weighted Class Standing Average. The Summary uses separate color bands for Quizzes, Participation/Output, and CS AVE to make these groups easier to follow.",
                "next_step": "Correct source records, then return to Summary until the gradebook is complete.",
            },
            {
                "code": "computation",
                "title": "How the Grade Is Computed",
                "purpose": "Explains the calculation in simple terms.",
                "check_first": ["Check the raw score and highest possible score.", "Confirm that all intended Participation/Output details were created.", "Check the component and period weights."],
                "actions": [],
                "avoid": "Raw Score Base-50 converts a score using: score percentage x 50, then add 50. Example: 15 out of 20 becomes 87.50. All faculty-created Participation/Output items are then averaged equally, whether they are recitations, assignments, seatwork, activities, or presentations; individual detail percentage weights are not used. The Participation/Output subcomponent weight, other component weights, and period weights still apply when TeacherMate+ produces the period and final grades.",
                "next_step": "Use Grade Explanation for a specific student and report a template issue if the assigned formula is wrong.",
            },
        ],
    },
    {
        "code": "submit",
        "title": "Submit, Reopen, or Correct Grades",
        "topics": [
            {
                "code": "submission",
                "title": "Submit Period Grades",
                "purpose": "Finalizes the current period gradebook and records it as Submitted.",
                "check_first": ["Resolve every missing required score and attendance record.", "Check all active students and non-active statuses.", "Review Summary and printed output if required.", "Confirm the correct class and period."],
                "actions": [
                    {"name": "Submit Period Grades", "does": "Finalizes period rows and records the gradebook submission.", "when": "Use it only when the gradebook is complete and checked.", "avoid": "Do not submit to test whether the gradebook is ready.", "result": "The status becomes Submitted, snapshots are stored, and normal editing stops.", "editable": "Only after an allowed reopen or approved correction route."},
                ],
                "avoid": "Submission is not the same as a separate approval or posting step. TeacherMate+ currently records ordinary gradebooks as Draft, Submitted, or Reopened.",
                "next_step": "Confirm that the period card and submission monitor show Submitted.",
                "workflow": {"starts": "Faculty prepares and submits the gradebook.", "reviews": "Faculty checks readiness first; authorized staff may monitor the submitted result.", "approves": "There is no separate ordinary gradebook approval status.", "receives": "TeacherMate+ stores the submitted gradebook and makes it available to permitted reports and monitors.", "complete": "The gradebook status is Submitted with complete required records.", "records": "Period grades, final grades when applicable, submission snapshots, submitter, time, and audit records."},
            },
            {
                "code": "reopen",
                "title": "Reopen an Unfinished Gradebook",
                "purpose": "Returns an eligible gradebook to editable status when more work is required.",
                "check_first": ["Check whether the gradebook is submitted.", "Check whether the deadline or lock has passed.", "Read the action shown on the period card."],
                "actions": [
                    {"name": "Reopen Before Deadline", "does": "Returns an eligible submitted gradebook to editable status before the deadline.", "when": "Use it when a valid correction is found before the deadline and policy permits.", "avoid": "Do not reopen without a clear reason and plan to resubmit.", "result": "The status becomes Reopened and editing resumes.", "editable": "Yes, until resubmission or a later lock."},
                    {"name": "Request Gradebook Reopen", "does": "Asks an assigned reviewer to restore access after a deadline or lock.", "when": "Use it for an overdue unsubmitted gradebook that still needs encoding or submission.", "avoid": "Do not use it for a submitted post-deadline grade change.", "result": "A pending request is sent to authorized scoped reviewers.", "editable": "Only after approval and during the allowed window."},
                ],
                "avoid": "After the deadline, changes to an already submitted gradebook normally belong in Correction of Grades.",
                "next_step": "If approved, finish the exact work requested and resubmit before access expires.",
            },
            {
                "code": "corrections",
                "title": "Correction of Grades",
                "purpose": "Requests an audited change to a grade that was already submitted.",
                "check_first": ["Choose the correct class, period, student, and activity.", "Confirm the original and corrected value.", "Prepare a clear reason and supporting document when required."],
                "actions": [
                    {"name": "Request Correction", "does": "Creates a correction request for review.", "when": "Use it for a genuine submitted-grade error.", "avoid": "Do not use it for an unfinished draft gradebook.", "result": "The request enters the configured approval route.", "editable": "The grade does not change until final approval."},
                    {"name": "Finalize Request", "does": "Confirms the correction details and sends them for review.", "when": "Use it after checking every student and value in the request.", "avoid": "Do not finalize incomplete or unsupported values.", "result": "Reviewers can approve or reject the request.", "editable": "Later changes may require a new request."},
                    {"name": "Official Report", "does": "Opens the correction document when available.", "when": "Use it after the required approval stage.", "avoid": "Do not present a pending request as approved.", "result": "A traceable correction reference is displayed or generated.", "editable": "No; it reflects the stored request."},
                ],
                "avoid": "Never ask an administrator to directly overwrite submitted grades outside the correction workflow.",
                "next_step": "Monitor the request until it is approved, rejected, closed, or returned for follow-up.",
                "workflow": {"starts": "Faculty or an authorized admin creates the request.", "reviews": "The configured reviewer checks the evidence and values.", "approves": "The final configured approver decides.", "receives": "Faculty and configured registrar recipients receive the result.", "complete": "Approved changes are applied and recomputed, or the request is formally closed.", "records": "Original/corrected values, reason, attachments, decisions, recomputed grades, and audit logs."},
            },
        ],
    },
    {
        "code": "reports",
        "title": "Reports, Student Support, and Security",
        "topics": [
            {
                "code": "performance",
                "title": "Class Performance and Parallel Sections",
                "purpose": "Provides a simple read-only view of class concerns and compares sections of the same course that you handle.",
                "check_first": ["Choose the correct class and grading period.", "Remember that missing records can make the snapshot incomplete.", "Use only your assigned sections."],
                "actions": [
                    {"name": "Class Performance", "does": "Shows class average, at-risk count, missing outputs, weakest component, and students requiring attention.", "when": "Use it after encoding current scores.", "avoid": "Do not use it to rank students.", "result": "A current read-only snapshot is computed using the official grading service.", "editable": "No grades or submissions change."},
                    {"name": "Explain", "does": "Opens the selected student's grade explanation beside the Current Grade value.", "when": "Use it to explain how the current period grade was computed.", "avoid": "Close the explanation before discussing another student.", "result": "The same private grade explanation used in Summary is displayed.", "editable": "No grade record changes."},
                    {"name": "Consultation View", "does": "Shows only one selected student's current grade, trend, missing outputs, weakest component, reason, and performance across available periods.", "when": "Use it during a private grade consultation.", "avoid": "Do not return to the class list while a student can see the screen.", "result": "Period and component trend graphs use only the selected student's computed records. No classmates are displayed.", "editable": "No records change."},
                    {"name": "Performance Trends", "does": "Compares your parallel sections for the same course, term, and grading period.", "when": "Use it when you handle at least two sections of the same course.", "avoid": "Do not compare different courses or another faculty member's sections.", "result": "A table, simple bars, and rule-based interpretation are displayed.", "editable": "No records change."},
                ],
                "avoid": "AT RISK takes priority when a computed grade is below the passing grade. INCOMPLETE is used when the student is not below passing but still has missing required outputs. Trend graphs and messages are rule-based explanations, not predictions.",
                "next_step": "Open the selected class or consultation view and verify the source scores before speaking with the student.",
            },
            {
                "code": "prediction",
                "title": "Grade Prediction and Student Intervention",
                "purpose": "Provides an unofficial estimate and a working list of students who may need academic follow-up.",
                "check_first": ["Confirm prediction is enabled for your role.", "Check whether activities or periods are still incomplete.", "Compare any concern with the official gradebook."],
                "actions": [
                    {"name": "Prediction", "does": "Shows current, possible, or target-needed estimates based on available records.", "when": "Use it for planning and early student support.", "avoid": "Do not present it as an official grade or guarantee.", "result": "An advisory calculation is displayed without changing official grades.", "editable": "What-if scenarios are temporary and do not edit the gradebook."},
                    {"name": "Student Intervention Monitor", "does": "Groups students who may need a record check or follow-up.", "when": "Use it to decide who needs attention first.", "avoid": "Do not label or discipline a student based only on a prediction.", "result": "A privacy-safe working list is shown.", "editable": "It does not change official grades."},
                ],
                "avoid": "Predictions depend on current saved records and can change when new scores are entered.",
                "next_step": "Review the student's actual records and provide appropriate academic support.",
            },
            {
                "code": "reports",
                "title": "Print and Export",
                "purpose": "Produces periodic grades, class tabulation, correction reports, or Final Clearance when available.",
                "check_first": ["Confirm class, period, student list, and submission status.", "Check names, dates, grades, and page scope.", "Use only the latest approved or submitted source record."],
                "actions": [
                    {"name": "Print Periodic Grades / Tabulation", "does": "Opens a printable grade report.", "when": "Use it after checking the Summary.", "avoid": "Do not distribute a Draft or Reopened gradebook as final.", "result": "A printable view or PDF is produced.", "editable": "Correct the source gradebook through the proper workflow, then regenerate."},
                    {"name": "Generate Final Clearance PDF", "does": "Creates the official faculty completion document when all required classes are complete.", "when": "Use it only when the page says all requirements are complete.", "avoid": "Do not treat a blocked clearance as a system error before checking each class.", "result": "A report with verification details is stored and generated.", "editable": "Regeneration follows current verified records."},
                    {"name": "Activity History", "does": "Shows a read-only timeline of recent grading, attendance, submission, and notice activity for your assigned classes.", "when": "Use it when you want the fuller story behind recent class changes.", "avoid": "Do not treat it as an editing page.", "result": "Recent updates are listed in time order with quick links back to the relevant page.", "editable": "No records change."},
                ],
                "avoid": "Prediction pages are advisory and must not be printed or presented as official grades.",
                "next_step": "Securely provide the report only to its authorized recipient.",
            },
            {
                "code": "notes",
                "title": "Private Reminders and Memos",
                "purpose": "Keeps personal teaching reminders and follow-up notes inside your account.",
                "check_first": ["Confirm the note belongs to your own faculty work.", "Keep wording professional and necessary.", "Avoid storing sensitive information that does not belong in a reminder."],
                "actions": [
                    {"name": "Save Memo / Reminder", "does": "Stores a private note or task for your account.", "when": "Use it for class follow-up, deadlines, or work reminders.", "avoid": "Do not use it as an official grade-change, disciplinary, or medical record.", "result": "The item appears in your reminder or memo workspace.", "editable": "It may be edited, completed, snoozed, pinned, or removed according to the page."},
                ],
                "avoid": "Private notes do not replace official communication or approval workflows.",
                "next_step": "Complete or remove the reminder when the follow-up is finished.",
            },
            {
                "code": "support-security",
                "title": "Student Support, Privacy, and Logout",
                "purpose": "Supports follow-up while protecting student information and your account.",
                "check_first": ["Use student information only for your assigned classes.", "Verify identity before discussing a grade.", "Save all changes before leaving a page."],
                "actions": [
                    {"name": "Logout", "does": "Ends your authenticated session.", "when": "Use it whenever leaving the device.", "avoid": "Do not rely only on closing the browser tab.", "result": "Protected actions require sign-in again.", "editable": "Unsaved work is not preserved."},
                ],
                "avoid": "Do not leave grade pages open on a shared device or share screenshots containing student records.",
                "next_step": "Log out and close the browser when work is complete.",
            },
        ],
    },
]
