from django.urls import path

from .views import (
    activity_scores_view,
    analytics_view,
    dashboard_view,
    faculty_assignment_accept_view,
    faculty_assignment_response_view,
    guide_view,
    guide_manual_view,
    my_courses_view,
    memo_center_view,
    memo_delete_view,
    memo_edit_view,
    memo_toggle_pin_view,
    quick_tour_disable_view,
    reminder_center_view,
    reminder_complete_view,
    reminder_snooze_view,
    student_at_risk_monitor_view,
    offering_grading_template_view,
    offering_enrollment_view,
    offering_periods_view,
    period_final_clearance_view,
    period_view_history_view,
    period_activity_delete_view,
    public_index_view,
    period_activities_view,
    period_attendance_view,
    period_prediction_view,
    period_prediction_guide_view,
    period_correction_official_report_view,
    period_correction_finalize_view,
    period_corrections_view,
    period_submit_view,
    period_summary_view,
)

app_name = "faculty_portal"

urlpatterns = [
    path("faculty/", public_index_view, name="public_index"),
    path("faculty/index/", public_index_view, name="public_index_alias"),
    path("faculty/guide/", guide_view, name="guide"),
    path("faculty/guide/manual/", guide_manual_view, name="guide_manual"),
    path("faculty/quick-tour/disable/", quick_tour_disable_view, name="quick_tour_disable"),
    path("faculty/dashboard/", dashboard_view, name="dashboard"),
    path("faculty/analytics/", analytics_view, name="analytics"),
    path("faculty/reminders/", reminder_center_view, name="reminder_center"),
    path("faculty/notes/", memo_center_view, name="memo_center"),
    path("faculty/notes/<int:memo_id>/edit/", memo_edit_view, name="memo_edit"),
    path("faculty/notes/<int:memo_id>/pin/", memo_toggle_pin_view, name="memo_toggle_pin"),
    path("faculty/notes/<int:memo_id>/delete/", memo_delete_view, name="memo_delete"),
    path("faculty/at-risk-monitor/", student_at_risk_monitor_view, name="student_at_risk_monitor"),
    path("faculty/reminders/<int:reminder_id>/complete/", reminder_complete_view, name="reminder_complete"),
    path("faculty/reminders/<int:reminder_id>/snooze/", reminder_snooze_view, name="reminder_snooze"),
    path("faculty/my-courses/", my_courses_view, name="my_courses"),
    path(
        "faculty/my-courses/assignments/<int:assignment_id>/accept/",
        faculty_assignment_accept_view,
        name="faculty_assignment_accept",
    ),
    path(
        "faculty/my-courses/assignments/<int:assignment_id>/respond/",
        faculty_assignment_response_view,
        name="faculty_assignment_response",
    ),
    path("faculty/my-courses/<int:offering_id>/periods/", offering_periods_view, name="offering_periods"),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/view-history/",
        period_view_history_view,
        name="period_view_history",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/final-clearance/",
        period_final_clearance_view,
        name="period_final_clearance",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/grading-template/",
        offering_grading_template_view,
        name="offering_grading_template",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/activities/",
        period_activities_view,
        name="period_activities",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/activities/<int:activity_id>/scores/",
        activity_scores_view,
        name="activity_scores",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/activities/<int:activity_id>/edit/",
        period_activities_view,
        name="period_activity_edit",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/activities/<int:activity_id>/delete/",
        period_activity_delete_view,
        name="period_activity_delete",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/attendance/",
        period_attendance_view,
        name="period_attendance",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/summary/",
        period_summary_view,
        name="period_summary",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/prediction/",
        period_prediction_view,
        name="period_prediction",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/prediction/guide/",
        period_prediction_guide_view,
        name="period_prediction_guide",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/submit/",
        period_submit_view,
        name="period_submit",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/corrections/",
        period_corrections_view,
        name="period_corrections",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/corrections/<int:request_id>/finalize/",
        period_correction_finalize_view,
        name="period_correction_finalize",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/periods/<int:period_id>/corrections/<int:request_id>/official-report/",
        period_correction_official_report_view,
        name="period_correction_official_report",
    ),
    path(
        "faculty/my-courses/<int:offering_id>/enrollment/",
        offering_enrollment_view,
        name="offering_enrollment",
    ),
]
