# Generated by Django 5.2.12 on 2026-03-20 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SYSTEM', 'System')], default='EMAIL', max_length=12)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('reference_type', models.CharField(blank=True, max_length=120, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_queue', to='tenants.campus')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_queue', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notification_queue',
                'ordering': ['status', 'scheduled_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recipient_user', 'channel', 'reference_type', 'reference_id', 'scheduled_at'), name='uq_notification_queue_reference')],
            },
        ),
    ]
