# Generated by Django 5.2.12 on 2026-03-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationqueue',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_queue', to=settings.AUTH_USER_MODEL),
        ),
    ]
