# Generated by Django 5.2.12 on 2026-04-04 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_facultyassignment_reminder_fields'),
        ('notifications', '0002_alter_notificationqueue_recipient_user'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('ACTIVITY_PREPARATION', 'Activity Preparation'), ('SCORE_ENCODING', 'Score Encoding'), ('ASSIGNMENT_ACCEPTANCE', 'Assignment Acceptance'), ('GRADE_SUBMISSION', 'Grade Submission'), ('CORRECTION_WINDOW', 'Correction Window'), ('AT_RISK_FOLLOWUP', 'At-Risk Follow-up'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('period_label', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remind_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('email_last_queued_at', models.DateTimeField(blank=True, null=True)),
                ('email_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_attempt_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminders', to='tenants.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_reminders', to=settings.AUTH_USER_MODEL)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminders', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminders', to='academics.courseoffering')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_reminders',
                'ordering': ['completed_at', 'snoozed_until', 'remind_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyReminderEmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=180)),
                ('priority', models.PositiveIntegerField(default=50)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminder_email_queue', to='tenants.campus')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminder_email_queue', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_queue', to='notifications.facultyreminder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_reminder_email_queue', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_reminder_email_queue',
                'ordering': ['status', 'scheduled_at', 'priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='facultyreminder',
            index=models.Index(fields=['tenant', 'faculty_user', 'remind_at'], name='idx_faculty_reminder_scope'),
        ),
        migrations.AddIndex(
            model_name='facultyreminder',
            index=models.Index(fields=['tenant', 'faculty_user', 'completed_at'], name='idx_faculty_reminder_done'),
        ),
        migrations.AddIndex(
            model_name='facultyreminderemailqueue',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_fremail_status_schedule'),
        ),
        migrations.AddIndex(
            model_name='facultyreminderemailqueue',
            index=models.Index(fields=['tenant', 'recipient_user', 'scheduled_at'], name='idx_fremail_scope'),
        ),
        migrations.AddConstraint(
            model_name='facultyreminderemailqueue',
            constraint=models.UniqueConstraint(fields=('dedupe_key',), name='uq_faculty_reminder_email_queue_dedupe'),
        ),
    ]
