# Generated by Django 5.2.12 on 2026-04-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_facultyassignment_reminder_fields'),
        ('notifications', '0003_facultyreminder_facultyreminderemailqueue_and_more'),
        ('students', '0003_update_student_uniqueness_scope'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo_type', models.CharField(choices=[('GENERAL', 'General'), ('CLASS', 'Class Memo'), ('STUDENT', 'Student Memo'), ('CUSTOM', 'Custom')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_memos', to='tenants.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_memos', to=settings.AUTH_USER_MODEL)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_memos', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_memos', to='academics.courseoffering')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_memos', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_memos', to='tenants.tenant')),
            ],
            options={
                'db_table': 'faculty_memos',
                'ordering': ['-is_pinned', '-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'faculty_user', 'is_pinned'], name='idx_faculty_memo_scope'), models.Index(fields=['tenant', 'faculty_user', 'memo_type'], name='idx_faculty_memo_type')],
            },
        ),
    ]
