# Generated by Django 5.2.12 on 2026-04-05 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_tenanttermgradingperiod_activegradingperiodsetting_and_more'),
        ('grading', '0014_gradingtemplateapprovalworkflow_and_more'),
        ('notifications', '0004_facultymemo'),
        ('tenants', '0002_alter_systemsetting_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyreminder',
            name='grade_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_reminders', to='grading.gradeactivity'),
        ),
        migrations.AddConstraint(
            model_name='facultyreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('grade_activity__isnull', False)), fields=('grade_activity',), name='uq_faculty_reminder_grade_activity'),
        ),
    ]
