# Generated by Django 5.2.12 on 2026-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_submissionreadinessnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreadinessnotificationlog',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submissionreadinessnotificationlog',
            name='status',
            field=models.CharField(choices=[('DRY_RUN', 'Dry run'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=12),
        ),
    ]
