# Generated by Django 5.2.12 on 2026-09-18 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_readiness_notification_attempt_tracking'),
        ('tenants', '0005_enable_existing_sis_api_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionDeadlineReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_local_date', models.DateField()),
                ('policy_version', models.CharField(default='v1', max_length=16)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('DISPATCHING', 'Dispatching'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED_PRE_SEND', 'Failed before send'), ('UNCERTAIN', 'Delivery uncertain')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'db_table': 'contribution_deadline_reminder_deliveries',
                'indexes': [models.Index(fields=['status', 'claimed_at'], name='idx_de_reminder_status_claim')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'faculty_user', 'deadline_local_date', 'policy_version'), name='uq_de_reminder_tenant_user_date_policy')],
            },
        ),
    ]
